import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import { checarAdminRequest, usuarioAdminAtual } from "@/lib/admin-guard";
import { registrarAuditoriaAdmin } from "@/lib/admin-audit";
import { obterIp } from "@/lib/rate-limit";
import { espelharDocumentoNoContatoZoho } from "@/lib/zoho-documentos";
import { validarArquivo, montarChaveStorage, sanitizarNomeExibicao } from "@/lib/upload-seguro";

export const runtime = "nodejs";

const TIPOS_VALIDOS = ["carta_aceite", "coe", "passagem_aerea", "carta_acomodacao", "visto", "visto_eua", "eta", "seguro_saude", "carta_transfer", "certificado_conclusao", "outro"];

export async function POST(request: Request) { if (!(await checarAdminRequest(request))) { return NextResponse.json({ ok: false, error: "Nao autorizado" }, { status: 401 }); } const formData = await request.formData(); const cpfRaw = String(formData.get("cpf") || ""); const cpf = cpfRaw.replace(/\D/g, ""); const tipoDocumento = String(formData.get("tipoDocumento") || ""); const arquivo = formData.get("arquivo") as File | null; if (!cpf || !TIPOS_VALIDOS.includes(tipoDocumento) || !arquivo) { return NextResponse.json({ ok: false, error: "Informe cpf, tipoDocumento valido e arquivo" }, { status: 400 }); } const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL as string; const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY as string; const supabase = createClient(supabaseUrl, serviceRoleKey); const { data: titular, error: titularError } = await supabase.from("titulares").select("id").eq("cpf", cpf).single(); if (titularError || !titular) { return NextResponse.json({ ok: false, error: "Titular nao encontrado para este CPF" }, { status: 404 }); } const buffer = await arquivo.arrayBuffer(); const validacao = validarArquivo(arquivo.size, buffer); if (!validacao.ok) { return NextResponse.json({ ok: false, error: validacao.erro }, { status: 400 }); } const nomeArquivo = sanitizarNomeExibicao(arquivo.name); const caminho = montarChaveStorage(titular.id, validacao.extensao); const { error: uploadError } = await supabase.storage.from("documentos-admin").upload(caminho, buffer, { contentType: validacao.mime }); if (uploadError) { return NextResponse.json({ ok: false, error: "Falha ao enviar arquivo" }, { status: 500 }); } const { error: insertError } = await supabase.from("documentos").insert({ titular_id: titular.id, tipo_documento: tipoDocumento, nome_arquivo: nomeArquivo, origem: "admin", storage_path: caminho, mime_type: validacao.mime, tamanho_bytes: arquivo.size, criado_por: "rodrigo@exp-tour.com" }); if (insertError) { return NextResponse.json({ ok: false, error: "Falha ao salvar registro do documento" }, { status: 500 }); } await espelharDocumentoNoContatoZoho(supabase, titular.id, nomeArquivo, buffer, validacao.mime); const usuario = (await usuarioAdminAtual()) ?? "bearer-secret"; await registrarAuditoriaAdmin(supabase, { usuario, acao: "documento.upload", alvo: cpf, detalhe: { tipoDocumento, nomeArquivo, titularId: titular.id }, ip: obterIp(request) }); return NextResponse.json({ ok: true }); }
