do $$ declare v_pid uuid; v_tid uuid; v_tpl uuid; v_fee uuid; begin

  select tenant_id into v_tid from campus where id='cea43266-51db-5e14-8c4b-b4f24611d620';
  select id into v_pid from product where campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and kind='accommodation' and attributes->>'slug'='bels-st-pauls-bay-malta-apartment-shared-none' and coalesce(attributes->>'category','')='' and archived_at is null;
  if v_pid is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes)
      values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','accommodation','Apartamento — quarto compartilhado, banheiro compartilhado, sem refeições','supplier','quotable','active','week',1,52,'{"seed": "planilha-2026-09", "slug": "bels-st-pauls-bay-malta-apartment-shared-none", "category": null, "availability_status": "Requer confirmação", "link": "https://belsmalta.com/accommodation/malta/self-catering-apartments/", "supplements": {"high_season_supplement": "30", "high_season_period": "28/jun a 29/ago", "low_season_discount": "30", "low_season_period": "3/jan a 28/fev e 1/nov a 31/dez", "private_bathroom_supplement": "70", "extra_night_fee": "70", "damage_deposit": "100", "other_supplement_fee": "10.5"}}'::jsonb) returning id into v_pid;
    insert into accommodation_detail (product_id, accommodation_type, room_type, bathroom_type, meal_plan) values (v_pid,'shared_apartment','shared_2','shared','none');
    insert into product_content (product_id, locale, description_html, highlights, exclusions) values (v_pid,'pt-BR','<p>Residência moderna no centro de Victoria (Gozo), a poucos minutos a pé da estação de ônibus principal; cozinha totalmente equipada, ar-condicionado/aquecimento, máquina de lavar e Wi-Fi de alta velocidade; áreas comuns para convívio com outros estudantes; limpeza semanal com troca de roupa de cama e toalhas; suporte 24/7 da equipe da escola.</p><p>Suplementos e condições: Suplemento de alta temporada: EUR 30/semana (28/jun a 29/ago); Desconto de baixa temporada: EUR 30/semana (3/jan a 28/fev e 1/nov a 31/dez); Suplemento banheiro privativo: EUR 70/semana; Noite extra: EUR 70; Depósito caução (reembolsável): EUR 100; Outro suplemento: EUR 10.5.</p><p>Ajuste sazonal da acomodação, por semana: alta temporada 28/jun a 29/ago +€30; baixa temporada 3/jan a 28/fev e 1/nov a 31/dez -€30; média temporada 1/mar a 27/jun e 30/ago a 31/out sem ajuste. O ajuste não se aplica a reservas de 12+ semanas. Taxa obrigatória: Eco Tax (18+) €10,50 por semana, máximo €22,50 por estadia. Transfer de chegada com check-in €50 (obrigatório) e transfer de saída €40 (opcional); pessoa adicional no mesmo transfer €10. Alteração de reserva €30. Opcionais por semana: banheiro privativo €70 (mediante solicitação, em quarto individual); seguro €17. Noite extra €70 por noite. Depósito caução reembolsável de €100 em dinheiro, recolhido no primeiro dia de aula para quem fica em residência BELS e devolvido no último dia se não houver danos. Semanas calculadas em estadias de 7 noites (check-in sábado/domingo, entrada 15:00 e saída 10:00); noites extras para chegada antecipada ou saída tardia são cobradas à parte. Fonte: BELS Malta Price List 2026 (atualização fev/2026).</p>','["Cozinha Equipada", "Ar-condicionado", "Aquecimento", "Máquina de Lavar", "Wi-Fi", "Áreas Comuns", "Limpeza Semanal", "Troca de Roupa de Cama e Toalhas", "Suporte 24/7", "Ideal para grupos e famílias que preferem independência e cozinhar"]'::jsonb,'["Menos indicado para quem busca imersão com família local"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','Apartamento — quarto compartilhado, banheiro compartilhado, sem refeições','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,225.0,0);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_pid);
  end if;

  select tenant_id into v_tid from campus where id='cea43266-51db-5e14-8c4b-b4f24611d620';
  select id into v_pid from product where campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and kind='accommodation' and attributes->>'slug'='bels-st-pauls-bay-malta-comfort-shared-none' and coalesce(attributes->>'category','')='Comfort' and archived_at is null;
  if v_pid is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes)
      values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','accommodation','Residência estudantil Comfort — quarto compartilhado, banheiro compartilhado, sem refeições','supplier','quotable','active','week',1,52,'{"seed": "planilha-2026-09", "slug": "bels-st-pauls-bay-malta-comfort-shared-none", "category": "Comfort", "availability_status": "Requer confirmação", "link": "https://belsmalta.com/accommodation/malta/bels-comfort-residence/", "supplements": {"high_season_supplement": "30", "high_season_period": "28/jun a 29/ago", "low_season_discount": "30", "low_season_period": "3/jan a 28/fev e 1/nov a 31/dez", "private_bathroom_supplement": "70", "extra_night_fee": "70", "damage_deposit": "100", "other_supplement_fee": "10.5"}}'::jsonb) returning id into v_pid;
    insert into accommodation_detail (product_id, accommodation_type, room_type, bathroom_type, meal_plan) values (v_pid,'residence','shared_2','shared','none');
    insert into product_content (product_id, locale, description_html, highlights, exclusions) values (v_pid,'pt-BR','<p>Quarto compartilhado (tipo twin, com outro estudante do mesmo sexo, mínimo 12 semanas para tarifa promocional). Banheiro compartilhado (banheiro privativo pode ser solicitado, sujeito a disponibilidade). Sem plano de refeições incluído — acomodação self-catering. Inclui: Wi-Fi, máquina de lavar, roupa de cama, toalhas e transporte de chegada do aeroporto. Não inclui: refeições.</p><p>Suplementos e condições: Suplemento de alta temporada: EUR 30/semana (28/jun a 29/ago); Desconto de baixa temporada: EUR 30/semana (3/jan a 28/fev e 1/nov a 31/dez); Suplemento banheiro privativo: EUR 70/semana; Noite extra: EUR 70; Depósito caução (reembolsável): EUR 100; Outro suplemento: EUR 10.5.</p><p>Ajuste sazonal da acomodação, por semana: alta temporada 28/jun a 29/ago +€30; baixa temporada 3/jan a 28/fev e 1/nov a 31/dez -€30; média temporada 1/mar a 27/jun e 30/ago a 31/out sem ajuste. O ajuste não se aplica a reservas de 12+ semanas. Taxa obrigatória: Eco Tax (18+) €10,50 por semana, máximo €22,50 por estadia. Transfer de chegada com check-in €50 (obrigatório) e transfer de saída €40 (opcional); pessoa adicional no mesmo transfer €10. Alteração de reserva €30. Opcionais por semana: banheiro privativo €70 (mediante solicitação, em quarto individual); seguro €17. Noite extra €70 por noite. Depósito caução reembolsável de €100 em dinheiro, recolhido no primeiro dia de aula para quem fica em residência BELS e devolvido no último dia se não houver danos. Semanas calculadas em estadias de 7 noites (check-in sábado/domingo, entrada 15:00 e saída 10:00); noites extras para chegada antecipada ou saída tardia são cobradas à parte. Fonte: BELS Malta Price List 2026 (atualização fev/2026).</p>','["Residência self-catering nas North Residences ou Westend, à beira-mar em St. Paul''s Bay, a 20 min a pé ou 5 min de ônibus da escola; cozinha totalmente equipada, máquina de lavar, TV e Wi-Fi; áreas comuns para socializar; limpeza semanal; opção mais econômica entre as residências da BELS; suporte 24/7 da equipe da escola.", "Ideal para estudantes de longa duração com orçamento reduzido"]'::jsonb,'["Menos indicado para quem quer mais conforto e privacidade"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','Residência estudantil Comfort — quarto compartilhado, banheiro compartilhado, sem refeições','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,195.0,0);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,8,165.0,1);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,12,135.0,2);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,24,130.0,3);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_pid);
  end if;

  select tenant_id into v_tid from campus where id='cea43266-51db-5e14-8c4b-b4f24611d620';
  select id into v_pid from product where campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and kind='accommodation' and attributes->>'slug'='bels-st-pauls-bay-malta-comfort-single-none' and coalesce(attributes->>'category','')='Comfort' and archived_at is null;
  if v_pid is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes)
      values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','accommodation','Residência estudantil Comfort — quarto individual, banheiro compartilhado, sem refeições','supplier','quotable','active','week',1,52,'{"seed": "planilha-2026-09", "slug": "bels-st-pauls-bay-malta-comfort-single-none", "category": "Comfort", "availability_status": "Requer confirmação", "link": "https://belsmalta.com/accommodation/malta/bels-comfort-residence/", "supplements": {"high_season_supplement": "30", "high_season_period": "28/jun a 29/ago", "low_season_discount": "30", "low_season_period": "3/jan a 28/fev e 1/nov a 31/dez", "private_bathroom_supplement": "70", "extra_night_fee": "70", "damage_deposit": "100", "other_supplement_fee": "10.5"}}'::jsonb) returning id into v_pid;
    insert into accommodation_detail (product_id, accommodation_type, room_type, bathroom_type, meal_plan) values (v_pid,'residence','private','shared','none');
    insert into product_content (product_id, locale, description_html, highlights, exclusions) values (v_pid,'pt-BR','<p>Quarto individual (privativo). Banheiro compartilhado (banheiro privativo pode ser solicitado, sujeito a disponibilidade). Sem plano de refeições incluído — acomodação self-catering. Inclui: Wi-Fi, máquina de lavar, roupa de cama, toalhas e transporte de chegada do aeroporto. Não inclui: refeições. Tarifas com desconto para estudantes de longa duração.</p><p>Suplementos e condições: Suplemento de alta temporada: EUR 30/semana (28/jun a 29/ago); Desconto de baixa temporada: EUR 30/semana (3/jan a 28/fev e 1/nov a 31/dez); Suplemento banheiro privativo: EUR 70/semana; Noite extra: EUR 70; Depósito caução (reembolsável): EUR 100; Outro suplemento: EUR 10.5.</p><p>Ajuste sazonal da acomodação, por semana: alta temporada 28/jun a 29/ago +€30; baixa temporada 3/jan a 28/fev e 1/nov a 31/dez -€30; média temporada 1/mar a 27/jun e 30/ago a 31/out sem ajuste. O ajuste não se aplica a reservas de 12+ semanas. Taxa obrigatória: Eco Tax (18+) €10,50 por semana, máximo €22,50 por estadia. Transfer de chegada com check-in €50 (obrigatório) e transfer de saída €40 (opcional); pessoa adicional no mesmo transfer €10. Alteração de reserva €30. Opcionais por semana: banheiro privativo €70 (mediante solicitação, em quarto individual); seguro €17. Noite extra €70 por noite. Depósito caução reembolsável de €100 em dinheiro, recolhido no primeiro dia de aula para quem fica em residência BELS e devolvido no último dia se não houver danos. Semanas calculadas em estadias de 7 noites (check-in sábado/domingo, entrada 15:00 e saída 10:00); noites extras para chegada antecipada ou saída tardia são cobradas à parte. Fonte: BELS Malta Price List 2026 (atualização fev/2026).</p>','["Residência self-catering nas North Residences ou Westend, à beira-mar em St. Paul''s Bay, a 20 min a pé ou 5 min de ônibus da escola; cozinha totalmente equipada, máquina de lavar, TV e Wi-Fi; áreas comuns para socializar; limpeza semanal; opção mais econômica entre as residências da BELS; suporte 24/7 da equipe da escola.", "Ideal para quem busca opção mais econômica, estadias longas"]'::jsonb,'["Menos indicado para quem quer amenidades superiores (ar-condicionado premium)"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','Residência estudantil Comfort — quarto individual, banheiro compartilhado, sem refeições','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,285.0,0);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,8,255.0,1);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,12,225.0,2);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,24,195.0,3);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_pid);
  end if;

  select tenant_id into v_tid from campus where id='cea43266-51db-5e14-8c4b-b4f24611d620';
  select id into v_pid from product where campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and kind='accommodation' and attributes->>'slug'='bels-st-pauls-bay-malta-homestay-shared-half-board' and coalesce(attributes->>'category','')='' and archived_at is null;
  if v_pid is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes)
      values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','accommodation','Casa de família — quarto compartilhado, banheiro compartilhado, meia pensão','supplier','quotable','active','week',1,52,'{"seed": "planilha-2026-09", "slug": "bels-st-pauls-bay-malta-homestay-shared-half-board", "category": null, "availability_status": "Pré-confirmado", "link": "https://belsmalta.com/accommodation/malta/home-stay/", "supplements": {"high_season_supplement": "30", "high_season_period": "28/jun a 29/ago", "low_season_discount": "30", "low_season_period": "3/jan a 28/fev e 1/nov a 31/dez", "private_bathroom_supplement": "70", "special_diet_supplement": "70", "extra_night_fee": "70", "other_supplement_fee": "10.5"}}'::jsonb) returning id into v_pid;
    insert into accommodation_detail (product_id, accommodation_type, room_type, bathroom_type, meal_plan) values (v_pid,'homestay','shared_2','shared','half_board');
    insert into product_content (product_id, locale, description_html, highlights, exclusions) values (v_pid,'pt-BR','<p>Residência estudantil da LSI Auckland com opção de suíte, oferecendo maior privacidade e conforto dentro do ambiente de convívio estudantil.</p><p>Suplementos e condições: Suplemento de alta temporada: EUR 30/semana (28/jun a 29/ago); Desconto de baixa temporada: EUR 30/semana (3/jan a 28/fev e 1/nov a 31/dez); Suplemento banheiro privativo: EUR 70/semana; Suplemento dieta especial: EUR 70/semana; Noite extra: EUR 70; Outro suplemento: EUR 10.5.</p><p>Ajuste sazonal da acomodação, por semana: alta temporada 28/jun a 29/ago +€30; baixa temporada 3/jan a 28/fev e 1/nov a 31/dez -€30; média temporada 1/mar a 27/jun e 30/ago a 31/out sem ajuste. O ajuste não se aplica a reservas de 12+ semanas. Taxa obrigatória: Eco Tax (18+) €10,50 por semana, máximo €22,50 por estadia. Transfer de chegada com check-in €50 (obrigatório) e transfer de saída €40 (opcional); pessoa adicional no mesmo transfer €10. Alteração de reserva €30. Opcionais por semana: banheiro privativo €70 (mediante solicitação, em quarto individual); dieta especial €70 (não cobrada para dietas vegetarianas); seguro €17. Noite extra €70 por noite. Semanas calculadas em estadias de 7 noites (check-in sábado/domingo, entrada 15:00 e saída 10:00); noites extras para chegada antecipada ou saída tardia são cobradas à parte. Fonte: BELS Malta Price List 2026 (atualização fev/2026).</p>','["Banheiro Privativo", "Privacidade", "Ideal para amigos que viajam juntos e querem imersão cultural"]'::jsonb,'["Menos indicado para quem busca total independência"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','Casa de família — quarto compartilhado, banheiro compartilhado, meia pensão','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,300.0,0);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_pid);
  end if;

  select tenant_id into v_tid from campus where id='cea43266-51db-5e14-8c4b-b4f24611d620';
  select id into v_pid from product where campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and kind='accommodation' and attributes->>'slug'='bels-st-pauls-bay-malta-homestay-single-half-board' and coalesce(attributes->>'category','')='' and archived_at is null;
  if v_pid is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes)
      values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','accommodation','Casa de família — quarto individual, banheiro compartilhado, meia pensão','supplier','quotable','active','week',1,52,'{"seed": "planilha-2026-09", "slug": "bels-st-pauls-bay-malta-homestay-single-half-board", "category": null, "availability_status": "Pré-confirmado", "link": "https://belsmalta.com/accommodation/malta/home-stay/", "supplements": {"high_season_supplement": "30", "high_season_period": "28/jun a 29/ago", "low_season_discount": "30", "low_season_period": "3/jan a 28/fev e 1/nov a 31/dez", "private_bathroom_supplement": "70", "special_diet_supplement": "70", "extra_night_fee": "70", "other_supplement_fee": "10.5"}}'::jsonb) returning id into v_pid;
    insert into accommodation_detail (product_id, accommodation_type, room_type, bathroom_type, meal_plan) values (v_pid,'homestay','private','shared','half_board');
    insert into product_content (product_id, locale, description_html, highlights, exclusions) values (v_pid,'pt-BR','<p>Família anfitriã da LSI New York, cuidadosamente selecionada para oferecer um ambiente acolhedor e seguro; ótima oportunidade para praticar o idioma no dia a dia e vivenciar a cultura local.</p><p>Suplementos e condições: Suplemento de alta temporada: EUR 30/semana (28/jun a 29/ago); Desconto de baixa temporada: EUR 30/semana (3/jan a 28/fev e 1/nov a 31/dez); Suplemento banheiro privativo: EUR 70/semana; Suplemento dieta especial: EUR 70/semana; Noite extra: EUR 70; Outro suplemento: EUR 10.5.</p><p>Ajuste sazonal da acomodação, por semana: alta temporada 28/jun a 29/ago +€30; baixa temporada 3/jan a 28/fev e 1/nov a 31/dez -€30; média temporada 1/mar a 27/jun e 30/ago a 31/out sem ajuste. O ajuste não se aplica a reservas de 12+ semanas. Taxa obrigatória: Eco Tax (18+) €10,50 por semana, máximo €22,50 por estadia. Transfer de chegada com check-in €50 (obrigatório) e transfer de saída €40 (opcional); pessoa adicional no mesmo transfer €10. Alteração de reserva €30. Opcionais por semana: banheiro privativo €70 (mediante solicitação, em quarto individual); dieta especial €70 (não cobrada para dietas vegetarianas); seguro €17. Noite extra €70 por noite. Semanas calculadas em estadias de 7 noites (check-in sábado/domingo, entrada 15:00 e saída 10:00); noites extras para chegada antecipada ou saída tardia são cobradas à parte. Fonte: BELS Malta Price List 2026 (atualização fev/2026).</p>','["Anfitriões Licenciados", "Ideal para quem busca imersão cultural e rotina em família maltesa"]'::jsonb,'["Menos indicado para quem busca total independência ou horários de refeição flexíveis"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','Casa de família — quarto individual, banheiro compartilhado, meia pensão','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,390.0,0);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_pid);
  end if;

  select tenant_id into v_tid from campus where id='cea43266-51db-5e14-8c4b-b4f24611d620';
  select id into v_pid from product where campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and kind='accommodation' and attributes->>'slug'='bels-st-pauls-bay-malta-residence-comfort-basic-shared-none' and coalesce(attributes->>'category','')='Comfort basic' and archived_at is null;
  if v_pid is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes)
      values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','accommodation','Residência estudantil Comfort basic — quarto compartilhado, banheiro compartilhado, sem refeições','supplier','quotable','active','week',1,52,'{"seed": "planilha-2026-09", "slug": "bels-st-pauls-bay-malta-residence-comfort-basic-shared-none", "category": "Comfort basic", "availability_status": "Requer confirmação", "link": "https://belsmalta.com/accommodation/malta/bels-comfort-residence/", "supplements": {"high_season_supplement": "30", "high_season_period": "28/jun a 29/ago", "low_season_discount": "30", "low_season_period": "3/jan a 28/fev e 1/nov a 31/dez", "private_bathroom_supplement": "70", "extra_night_fee": "70", "damage_deposit": "100", "other_supplement_fee": "10.5"}}'::jsonb) returning id into v_pid;
    insert into accommodation_detail (product_id, accommodation_type, room_type, bathroom_type, meal_plan) values (v_pid,'residence','shared_2','shared','none');
    insert into product_content (product_id, locale, description_html, highlights, exclusions) values (v_pid,'pt-BR','<p>Quarto duplo (twin) compartilhado com outro estudante do mesmo gênero, na categoria Comfort Basic. Banheiro compartilhado. Sem plano de refeições — self-catering, com cozinha equipada. Inclui: Wi-Fi, máquina de lavar, roupa de cama, toalhas e limpeza semanal. Não inclui: refeições. Valor por pessoa/semana, com desconto progressivo a partir de 8 semanas.</p><p>Suplementos e condições: Suplemento de alta temporada: EUR 30/semana (28/jun a 29/ago); Desconto de baixa temporada: EUR 30/semana (3/jan a 28/fev e 1/nov a 31/dez); Suplemento banheiro privativo: EUR 70/semana; Noite extra: EUR 70; Depósito caução (reembolsável): EUR 100; Outro suplemento: EUR 10.5.</p><p>Ajuste sazonal da acomodação, por semana: alta temporada 28/jun a 29/ago +€30; baixa temporada 3/jan a 28/fev e 1/nov a 31/dez -€30; média temporada 1/mar a 27/jun e 30/ago a 31/out sem ajuste. O ajuste não se aplica a reservas de 12+ semanas. Taxa obrigatória: Eco Tax (18+) €10,50 por semana, máximo €22,50 por estadia. Transfer de chegada com check-in €50 (obrigatório) e transfer de saída €40 (opcional); pessoa adicional no mesmo transfer €10. Alteração de reserva €30. Opcionais por semana: banheiro privativo €70 (mediante solicitação, em quarto individual); seguro €17. Noite extra €70 por noite. Depósito caução reembolsável de €100 em dinheiro, recolhido no primeiro dia de aula para quem fica em residência BELS e devolvido no último dia se não houver danos. Semanas calculadas em estadias de 7 noites (check-in sábado/domingo, entrada 15:00 e saída 10:00); noites extras para chegada antecipada ou saída tardia são cobradas à parte. Fonte: BELS Malta Price List 2026 (atualização fev/2026).</p>','["Residência self-catering nas North Residences ou Westend, à beira-mar em St. Paul''s Bay, a 20 min a pé ou 5 min de ônibus da escola; cozinha totalmente equipada, máquina de lavar, TV e Wi-Fi; áreas comuns para socializar; limpeza semanal com troca de roupa de cama e toalhas; é a categoria mais econômica de residência da BELS; suporte 24/7 da equipe da escola.", "Ideal para quem quer o menor preço possível em residência e não se incomoda de dividir o quarto"]'::jsonb,'["Menos indicado para quem precisa de quarto individual ou banheiro privativo"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','Residência estudantil Comfort basic — quarto compartilhado, banheiro compartilhado, sem refeições','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,165.0,0);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,8,155.0,1);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,12,125.0,2);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,24,125.0,3);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_pid);
  end if;

  select tenant_id into v_tid from campus where id='cea43266-51db-5e14-8c4b-b4f24611d620';
  select id into v_pid from product where campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and kind='accommodation' and attributes->>'slug'='bels-st-pauls-bay-malta-residence-shared-none' and coalesce(attributes->>'category','')='' and archived_at is null;
  if v_pid is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes)
      values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','accommodation','Residência estudantil — quarto compartilhado, banheiro compartilhado, sem refeições','supplier','quotable','active','week',1,52,'{"seed": "planilha-2026-09", "slug": "bels-st-pauls-bay-malta-residence-shared-none", "category": null, "availability_status": "Requer confirmação", "link": "https://belsmalta.com/accommodation/malta/bels-superior-residence/", "supplements": {"high_season_supplement": "30", "high_season_period": "28/jun a 29/ago", "low_season_discount": "30", "low_season_period": "3/jan a 28/fev e 1/nov a 31/dez", "private_bathroom_supplement": "70", "extra_night_fee": "70", "damage_deposit": "100", "other_supplement_fee": "10.5"}}'::jsonb) returning id into v_pid;
    insert into accommodation_detail (product_id, accommodation_type, room_type, bathroom_type, meal_plan) values (v_pid,'residence','shared_2','shared','none');
    insert into product_content (product_id, locale, description_html, highlights, exclusions) values (v_pid,'pt-BR','<p>Quarto compartilhado (tipo twin, com outro estudante do mesmo sexo). Banheiro compartilhado (banheiro privativo disponível como opção adicional, mediante taxa extra). Sem plano de refeições incluído — acomodação self-catering, com cozinha equipada. Inclui: Wi-Fi, ar-condicionado/aquecimento, máquina de lavar, roupa de cama, toalhas e transporte de chegada do aeroporto. Não inclui: refeições.</p><p>Suplementos e condições: Suplemento de alta temporada: EUR 30/semana (28/jun a 29/ago); Desconto de baixa temporada: EUR 30/semana (3/jan a 28/fev e 1/nov a 31/dez); Suplemento banheiro privativo: EUR 70/semana; Noite extra: EUR 70; Depósito caução (reembolsável): EUR 100; Outro suplemento: EUR 10.5.</p><p>Ajuste sazonal da acomodação, por semana: alta temporada 28/jun a 29/ago +€30; baixa temporada 3/jan a 28/fev e 1/nov a 31/dez -€30; média temporada 1/mar a 27/jun e 30/ago a 31/out sem ajuste. O ajuste não se aplica a reservas de 12+ semanas. Taxa obrigatória: Eco Tax (18+) €10,50 por semana, máximo €22,50 por estadia. Transfer de chegada com check-in €50 (obrigatório) e transfer de saída €40 (opcional); pessoa adicional no mesmo transfer €10. Alteração de reserva €30. Opcionais por semana: banheiro privativo €70 (mediante solicitação, em quarto individual); seguro €17. Noite extra €70 por noite. Depósito caução reembolsável de €100 em dinheiro, recolhido no primeiro dia de aula para quem fica em residência BELS e devolvido no último dia se não houver danos. Semanas calculadas em estadias de 7 noites (check-in sábado/domingo, entrada 15:00 e saída 10:00); noites extras para chegada antecipada ou saída tardia são cobradas à parte. Fonte: BELS Malta Price List 2026 (atualização fev/2026).</p>','["Residência moderna e murada em Xemxija, à beira-mar em St. Paul''s Bay, a 20 min a pé ou 5 min de ônibus da escola; cozinha totalmente equipada, máquina de lavar, ar-condicionado/aquecimento, TV e Wi-Fi de alta velocidade; áreas comuns para convívio com outros estudantes; limpeza semanal; suporte 24/7 da equipe da escola.", "Ideal para quem viaja com amigos e quer dividir custos"]'::jsonb,'["Menos indicado para quem precisa de total privacidade"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','Residência estudantil — quarto compartilhado, banheiro compartilhado, sem refeições','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,225.0,0);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,8,195.0,1);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,12,165.0,2);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,24,145.0,3);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_pid);
  end if;

  select tenant_id into v_tid from campus where id='cea43266-51db-5e14-8c4b-b4f24611d620';
  select id into v_pid from product where campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and kind='accommodation' and attributes->>'slug'='bels-st-pauls-bay-malta-residence-single-none' and coalesce(attributes->>'category','')='' and archived_at is null;
  if v_pid is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes)
      values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','accommodation','Residência estudantil — quarto individual, banheiro compartilhado, sem refeições','supplier','quotable','active','week',1,52,'{"seed": "planilha-2026-09", "slug": "bels-st-pauls-bay-malta-residence-single-none", "category": null, "availability_status": "Requer confirmação", "link": "https://belsmalta.com/accommodation/malta/bels-superior-residence/", "supplements": {"high_season_supplement": "30", "high_season_period": "28/jun a 29/ago", "low_season_discount": "30", "low_season_period": "3/jan a 28/fev e 1/nov a 31/dez", "private_bathroom_supplement": "70", "extra_night_fee": "70", "damage_deposit": "100", "other_supplement_fee": "10.5"}}'::jsonb) returning id into v_pid;
    insert into accommodation_detail (product_id, accommodation_type, room_type, bathroom_type, meal_plan) values (v_pid,'residence','private','shared','none');
    insert into product_content (product_id, locale, description_html, highlights, exclusions) values (v_pid,'pt-BR','<p>Quarto individual (privativo). Banheiro compartilhado (banheiro privativo disponível como opção adicional, mediante taxa extra). Sem plano de refeições incluído — acomodação self-catering, com cozinha equipada. Inclui: Wi-Fi, ar-condicionado/aquecimento, máquina de lavar, roupa de cama, toalhas e transporte de chegada do aeroporto. Não inclui: refeições.</p><p>Suplementos e condições: Suplemento de alta temporada: EUR 30/semana (28/jun a 29/ago); Desconto de baixa temporada: EUR 30/semana (3/jan a 28/fev e 1/nov a 31/dez); Suplemento banheiro privativo: EUR 70/semana; Noite extra: EUR 70; Depósito caução (reembolsável): EUR 100; Outro suplemento: EUR 10.5.</p><p>Ajuste sazonal da acomodação, por semana: alta temporada 28/jun a 29/ago +€30; baixa temporada 3/jan a 28/fev e 1/nov a 31/dez -€30; média temporada 1/mar a 27/jun e 30/ago a 31/out sem ajuste. O ajuste não se aplica a reservas de 12+ semanas. Taxa obrigatória: Eco Tax (18+) €10,50 por semana, máximo €22,50 por estadia. Transfer de chegada com check-in €50 (obrigatório) e transfer de saída €40 (opcional); pessoa adicional no mesmo transfer €10. Alteração de reserva €30. Opcionais por semana: banheiro privativo €70 (mediante solicitação, em quarto individual); seguro €17. Noite extra €70 por noite. Depósito caução reembolsável de €100 em dinheiro, recolhido no primeiro dia de aula para quem fica em residência BELS e devolvido no último dia se não houver danos. Semanas calculadas em estadias de 7 noites (check-in sábado/domingo, entrada 15:00 e saída 10:00); noites extras para chegada antecipada ou saída tardia são cobradas à parte. Fonte: BELS Malta Price List 2026 (atualização fev/2026).</p>','["Residência moderna e murada em Xemxija, à beira-mar em St. Paul''s Bay, a 20 min a pé ou 5 min de ônibus da escola; cozinha totalmente equipada, máquina de lavar, ar-condicionado/aquecimento, TV e Wi-Fi de alta velocidade; áreas comuns para convívio com outros estudantes; limpeza semanal; suporte 24/7 da equipe da escola.", "Ideal para quem busca praticidade, vida em comunidade, orçamento médio"]'::jsonb,'["Menos indicado para quem exige banheiro privativo garantido sem custo extra"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','Residência estudantil — quarto individual, banheiro compartilhado, sem refeições','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,320.0,0);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,8,290.0,1);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,12,260.0,2);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,24,230.0,3);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_pid);
  end if;

  select tenant_id into v_tid from campus where id='cea43266-51db-5e14-8c4b-b4f24611d620';
  select id into v_pid from product where campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and kind='accommodation' and attributes->>'slug'='bels-st-pauls-bay-malta-residence-superior-plus-ensuite-shared-none' and coalesce(attributes->>'category','')='Superior plus' and archived_at is null;
  if v_pid is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes)
      values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','accommodation','Residência estudantil Superior plus — quarto compartilhado, banheiro privativo, sem refeições','supplier','quotable','active','week',1,52,'{"seed": "planilha-2026-09", "slug": "bels-st-pauls-bay-malta-residence-superior-plus-ensuite-shared-none", "category": "Superior plus", "availability_status": "Requer confirmação", "link": "https://belsmalta.com/accommodation/malta/bels-superior-residence/", "supplements": {"high_season_supplement": "30", "high_season_period": "28/jun a 29/ago", "low_season_discount": "30", "low_season_period": "3/jan a 28/fev e 1/nov a 31/dez", "extra_night_fee": "70", "damage_deposit": "100", "other_supplement_fee": "10.5"}}'::jsonb) returning id into v_pid;
    insert into accommodation_detail (product_id, accommodation_type, room_type, bathroom_type, meal_plan) values (v_pid,'residence','shared_2','private','none');
    insert into product_content (product_id, locale, description_html, highlights, exclusions) values (v_pid,'pt-BR','<p>Quarto duplo (twin) compartilhado com outro estudante do mesmo gênero, na categoria Superior Plus com banheiro privativo (ensuite) incluído. Sem plano de refeições — self-catering, com cozinha equipada. Inclui: banheiro privativo, Wi-Fi de alta velocidade, ar-condicionado/aquecimento, máquina de lavar, roupa de cama, toalhas e limpeza semanal. Não inclui: refeições. Valor por pessoa/semana, com desconto progressivo a partir de 8 semanas.</p><p>Suplementos e condições: Suplemento de alta temporada: EUR 30/semana (28/jun a 29/ago); Desconto de baixa temporada: EUR 30/semana (3/jan a 28/fev e 1/nov a 31/dez); Noite extra: EUR 70; Depósito caução (reembolsável): EUR 100; Outro suplemento: EUR 10.5.</p><p>Ajuste sazonal da acomodação, por semana: alta temporada 28/jun a 29/ago +€30; baixa temporada 3/jan a 28/fev e 1/nov a 31/dez -€30; média temporada 1/mar a 27/jun e 30/ago a 31/out sem ajuste. O ajuste não se aplica a reservas de 12+ semanas. Taxa obrigatória: Eco Tax (18+) €10,50 por semana, máximo €22,50 por estadia. Transfer de chegada com check-in €50 (obrigatório) e transfer de saída €40 (opcional); pessoa adicional no mesmo transfer €10. Alteração de reserva €30. Opcionais por semana: seguro €17. Noite extra €70 por noite. Depósito caução reembolsável de €100 em dinheiro, recolhido no primeiro dia de aula para quem fica em residência BELS e devolvido no último dia se não houver danos. Semanas calculadas em estadias de 7 noites (check-in sábado/domingo, entrada 15:00 e saída 10:00); noites extras para chegada antecipada ou saída tardia são cobradas à parte. Fonte: BELS Malta Price List 2026 (atualização fev/2026).</p>','["Residência superior recém-construída em condomínio fechado em Xemxija, St. Paul''s Bay, à beira-mar, a 20 min a pé ou 5 min de ônibus da escola (parada de ônibus na porta); apartamentos de 3 quartos com no máximo 6 estudantes; cozinha totalmente equipada, ar-condicionado/aquecimento, máquina de lavar, tábua de passar, TV e Wi-Fi de alta velocidade; áreas comuns de cozinha e estar; limpeza semanal com troca de roupa de cama e toalhas; suporte 24/7 da equipe da escola.", "Ideal para quem quer banheiro privativo sem pagar por quarto individual"]'::jsonb,'["Menos indicado para quem precisa do menor preço possível"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','Residência estudantil Superior plus — quarto compartilhado, banheiro privativo, sem refeições','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,295.0,0);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,8,265.0,1);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,12,235.0,2);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,24,205.0,3);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_pid);
  end if;

  select tenant_id into v_tid from campus where id='cea43266-51db-5e14-8c4b-b4f24611d620';
  select id into v_pid from product where campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and kind='accommodation' and attributes->>'slug'='bels-st-pauls-bay-malta-residence-superior-plus-ensuite-single-none' and coalesce(attributes->>'category','')='Superior plus' and archived_at is null;
  if v_pid is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes)
      values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','accommodation','Residência estudantil Superior plus — quarto individual, banheiro privativo, sem refeições','supplier','quotable','active','week',1,52,'{"seed": "planilha-2026-09", "slug": "bels-st-pauls-bay-malta-residence-superior-plus-ensuite-single-none", "category": "Superior plus", "availability_status": "Requer confirmação", "link": "https://belsmalta.com/accommodation/malta/bels-superior-residence/", "supplements": {"high_season_supplement": "30", "high_season_period": "28/jun a 29/ago", "low_season_discount": "30", "low_season_period": "3/jan a 28/fev e 1/nov a 31/dez", "extra_night_fee": "70", "damage_deposit": "100", "other_supplement_fee": "10.5"}}'::jsonb) returning id into v_pid;
    insert into accommodation_detail (product_id, accommodation_type, room_type, bathroom_type, meal_plan) values (v_pid,'residence','private','private','none');
    insert into product_content (product_id, locale, description_html, highlights, exclusions) values (v_pid,'pt-BR','<p>Quarto individual (privativo) na categoria Superior Plus com banheiro privativo (ensuite) incluído. Sem plano de refeições — self-catering, com cozinha equipada. Inclui: banheiro privativo, Wi-Fi de alta velocidade, ar-condicionado/aquecimento, máquina de lavar, roupa de cama, toalhas e limpeza semanal. Não inclui: refeições. Valor por pessoa/semana, com desconto progressivo a partir de 8 semanas.</p><p>Suplementos e condições: Suplemento de alta temporada: EUR 30/semana (28/jun a 29/ago); Desconto de baixa temporada: EUR 30/semana (3/jan a 28/fev e 1/nov a 31/dez); Noite extra: EUR 70; Depósito caução (reembolsável): EUR 100; Outro suplemento: EUR 10.5.</p><p>Ajuste sazonal da acomodação, por semana: alta temporada 28/jun a 29/ago +€30; baixa temporada 3/jan a 28/fev e 1/nov a 31/dez -€30; média temporada 1/mar a 27/jun e 30/ago a 31/out sem ajuste. O ajuste não se aplica a reservas de 12+ semanas. Taxa obrigatória: Eco Tax (18+) €10,50 por semana, máximo €22,50 por estadia. Transfer de chegada com check-in €50 (obrigatório) e transfer de saída €40 (opcional); pessoa adicional no mesmo transfer €10. Alteração de reserva €30. Opcionais por semana: seguro €17. Noite extra €70 por noite. Depósito caução reembolsável de €100 em dinheiro, recolhido no primeiro dia de aula para quem fica em residência BELS e devolvido no último dia se não houver danos. Semanas calculadas em estadias de 7 noites (check-in sábado/domingo, entrada 15:00 e saída 10:00); noites extras para chegada antecipada ou saída tardia são cobradas à parte. Fonte: BELS Malta Price List 2026 (atualização fev/2026).</p>','["Residência superior recém-construída em condomínio fechado em Xemxija, St. Paul''s Bay, à beira-mar, a 20 min a pé ou 5 min de ônibus da escola (parada de ônibus na porta); apartamentos de 3 quartos com no máximo 6 estudantes; cozinha totalmente equipada, ar-condicionado/aquecimento, máquina de lavar, tábua de passar, TV e Wi-Fi de alta velocidade; áreas comuns de cozinha e estar; limpeza semanal com troca de roupa de cama e toalhas; suporte 24/7 da equipe da escola.", "Ideal para quem quer privacidade total: quarto individual e banheiro privativo"]'::jsonb,'["Menos indicado para quem tem orçamento apertado ou quer refeições incluídas"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','Residência estudantil Superior plus — quarto individual, banheiro privativo, sem refeições','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,425.0,0);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,8,395.0,1);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,12,365.0,2);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,24,335.0,3);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_pid);
  end if;

  select tenant_id into v_tid from campus where id='cea43266-51db-5e14-8c4b-b4f24611d620';
  select id into v_pid from product where campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and kind='accommodation' and attributes->>'slug'='bels-st-pauls-bay-malta-residence-superior-plus-shared-none' and coalesce(attributes->>'category','')='Superior plus' and archived_at is null;
  if v_pid is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes)
      values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','accommodation','Residência estudantil Superior plus — quarto compartilhado, banheiro compartilhado, sem refeições','supplier','quotable','active','week',1,52,'{"seed": "planilha-2026-09", "slug": "bels-st-pauls-bay-malta-residence-superior-plus-shared-none", "category": "Superior plus", "availability_status": "Requer confirmação", "link": "https://belsmalta.com/accommodation/malta/bels-superior-residence/", "supplements": {"high_season_supplement": "30", "high_season_period": "28/jun a 29/ago", "low_season_discount": "30", "low_season_period": "3/jan a 28/fev e 1/nov a 31/dez", "private_bathroom_supplement": "70", "extra_night_fee": "70", "damage_deposit": "100", "other_supplement_fee": "10.5"}}'::jsonb) returning id into v_pid;
    insert into accommodation_detail (product_id, accommodation_type, room_type, bathroom_type, meal_plan) values (v_pid,'residence','shared_2','shared','none');
    insert into product_content (product_id, locale, description_html, highlights, exclusions) values (v_pid,'pt-BR','<p>Quarto duplo (twin) compartilhado com outro estudante do mesmo gênero, na categoria Superior Plus. Banheiro compartilhado (banheiro privativo pode ser solicitado por 70 euros/semana). Sem plano de refeições — self-catering, com cozinha equipada. Inclui: Wi-Fi de alta velocidade, ar-condicionado/aquecimento, máquina de lavar, roupa de cama, toalhas e limpeza semanal. Não inclui: refeições. Valor por pessoa/semana, com desconto progressivo a partir de 8 semanas.</p><p>Suplementos e condições: Suplemento de alta temporada: EUR 30/semana (28/jun a 29/ago); Desconto de baixa temporada: EUR 30/semana (3/jan a 28/fev e 1/nov a 31/dez); Suplemento banheiro privativo: EUR 70/semana; Noite extra: EUR 70; Depósito caução (reembolsável): EUR 100; Outro suplemento: EUR 10.5.</p><p>Ajuste sazonal da acomodação, por semana: alta temporada 28/jun a 29/ago +€30; baixa temporada 3/jan a 28/fev e 1/nov a 31/dez -€30; média temporada 1/mar a 27/jun e 30/ago a 31/out sem ajuste. O ajuste não se aplica a reservas de 12+ semanas. Taxa obrigatória: Eco Tax (18+) €10,50 por semana, máximo €22,50 por estadia. Transfer de chegada com check-in €50 (obrigatório) e transfer de saída €40 (opcional); pessoa adicional no mesmo transfer €10. Alteração de reserva €30. Opcionais por semana: banheiro privativo €70 (mediante solicitação, em quarto individual); seguro €17. Noite extra €70 por noite. Depósito caução reembolsável de €100 em dinheiro, recolhido no primeiro dia de aula para quem fica em residência BELS e devolvido no último dia se não houver danos. Semanas calculadas em estadias de 7 noites (check-in sábado/domingo, entrada 15:00 e saída 10:00); noites extras para chegada antecipada ou saída tardia são cobradas à parte. Fonte: BELS Malta Price List 2026 (atualização fev/2026).</p>','["Residência superior recém-construída em condomínio fechado em Xemxija, St. Paul''s Bay, à beira-mar, a 20 min a pé ou 5 min de ônibus da escola (parada de ônibus na porta); apartamentos de 3 quartos com no máximo 6 estudantes; cozinha totalmente equipada, ar-condicionado/aquecimento, máquina de lavar, tábua de passar, TV e Wi-Fi de alta velocidade; áreas comuns de cozinha e estar; limpeza semanal com troca de roupa de cama e toalhas; suporte 24/7 da equipe da escola.", "Ideal para quem quer residência de padrão superior dividindo o quarto para economizar"]'::jsonb,'["Menos indicado para quem precisa de banheiro privativo incluído no preço"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','Residência estudantil Superior plus — quarto compartilhado, banheiro compartilhado, sem refeições','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,260.0,0);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,8,230.0,1);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,12,200.0,2);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,24,170.0,3);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_pid);
  end if;

  select tenant_id into v_tid from campus where id='cea43266-51db-5e14-8c4b-b4f24611d620';
  select id into v_pid from product where campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and kind='accommodation' and attributes->>'slug'='bels-st-pauls-bay-malta-residence-superior-plus-single-none' and coalesce(attributes->>'category','')='Superior plus' and archived_at is null;
  if v_pid is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes)
      values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','accommodation','Residência estudantil Superior plus — quarto individual, banheiro compartilhado, sem refeições','supplier','quotable','active','week',1,52,'{"seed": "planilha-2026-09", "slug": "bels-st-pauls-bay-malta-residence-superior-plus-single-none", "category": "Superior plus", "availability_status": "Requer confirmação", "link": "https://belsmalta.com/accommodation/malta/bels-superior-residence/", "supplements": {"high_season_supplement": "30", "high_season_period": "28/jun a 29/ago", "low_season_discount": "30", "low_season_period": "3/jan a 28/fev e 1/nov a 31/dez", "private_bathroom_supplement": "70", "extra_night_fee": "70", "damage_deposit": "100", "other_supplement_fee": "10.5"}}'::jsonb) returning id into v_pid;
    insert into accommodation_detail (product_id, accommodation_type, room_type, bathroom_type, meal_plan) values (v_pid,'residence','private','shared','none');
    insert into product_content (product_id, locale, description_html, highlights, exclusions) values (v_pid,'pt-BR','<p>Quarto individual (privativo) na categoria Superior Plus. Banheiro compartilhado (banheiro privativo pode ser solicitado por 70 euros/semana). Sem plano de refeições — self-catering, com cozinha equipada. Inclui: Wi-Fi de alta velocidade, ar-condicionado/aquecimento, máquina de lavar, roupa de cama, toalhas e limpeza semanal. Não inclui: refeições. Valor por pessoa/semana, com desconto progressivo a partir de 8 semanas.</p><p>Suplementos e condições: Suplemento de alta temporada: EUR 30/semana (28/jun a 29/ago); Desconto de baixa temporada: EUR 30/semana (3/jan a 28/fev e 1/nov a 31/dez); Suplemento banheiro privativo: EUR 70/semana; Noite extra: EUR 70; Depósito caução (reembolsável): EUR 100; Outro suplemento: EUR 10.5.</p><p>Ajuste sazonal da acomodação, por semana: alta temporada 28/jun a 29/ago +€30; baixa temporada 3/jan a 28/fev e 1/nov a 31/dez -€30; média temporada 1/mar a 27/jun e 30/ago a 31/out sem ajuste. O ajuste não se aplica a reservas de 12+ semanas. Taxa obrigatória: Eco Tax (18+) €10,50 por semana, máximo €22,50 por estadia. Transfer de chegada com check-in €50 (obrigatório) e transfer de saída €40 (opcional); pessoa adicional no mesmo transfer €10. Alteração de reserva €30. Opcionais por semana: banheiro privativo €70 (mediante solicitação, em quarto individual); seguro €17. Noite extra €70 por noite. Depósito caução reembolsável de €100 em dinheiro, recolhido no primeiro dia de aula para quem fica em residência BELS e devolvido no último dia se não houver danos. Semanas calculadas em estadias de 7 noites (check-in sábado/domingo, entrada 15:00 e saída 10:00); noites extras para chegada antecipada ou saída tardia são cobradas à parte. Fonte: BELS Malta Price List 2026 (atualização fev/2026).</p>','["Residência superior recém-construída em condomínio fechado em Xemxija, St. Paul''s Bay, à beira-mar, a 20 min a pé ou 5 min de ônibus da escola (parada de ônibus na porta); apartamentos de 3 quartos com no máximo 6 estudantes; cozinha totalmente equipada, ar-condicionado/aquecimento, máquina de lavar, tábua de passar, TV e Wi-Fi de alta velocidade; áreas comuns de cozinha e estar; limpeza semanal com troca de roupa de cama e toalhas; suporte 24/7 da equipe da escola.", "Ideal para quem quer quarto só seu em residência de padrão superior, mantendo a vida em comunidade"]'::jsonb,'["Menos indicado para quem busca a opção mais econômica ou quer refeições incluídas"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','Residência estudantil Superior plus — quarto individual, banheiro compartilhado, sem refeições','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,355.0,0);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,8,325.0,1);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,12,295.0,2);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,24,265.0,3);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_pid);
  end if;
end $$;