do $$ declare v_pid uuid; v_tid uuid; v_tpl uuid; v_fee uuid; begin

  select tenant_id into v_tid from campus where id='1545ba6a-1aad-5804-8f03-9515c842937a';
  select id into v_pid from product where campus_id='1545ba6a-1aad-5804-8f03-9515c842937a' and kind='accommodation' and attributes->>'slug'='gse-st-julian-malta-apartment-shared-none' and coalesce(attributes->>'category','')='' and archived_at is null;
  if v_pid is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes)
      values (v_tid,'1545ba6a-1aad-5804-8f03-9515c842937a','accommodation','Apartamento — quarto compartilhado, banheiro privativo, sem refeições','supplier','quotable','active','week',1,52,'{"seed": "planilha-2026-09", "slug": "gse-st-julian-malta-apartment-shared-none", "category": null, "availability_status": "Requer confirmação", "link": "https://english-malta.com/accommodation/apartments-malta/", "supplements": {"high_season_period": "sob consulta", "low_season_period": "sob consulta"}}'::jsonb) returning id into v_pid;
    insert into accommodation_detail (product_id, accommodation_type, room_type, bathroom_type, meal_plan) values (v_pid,'shared_apartment','shared_2','private','none');
    insert into product_content (product_id, locale, description_html, highlights, exclusions) values (v_pid,'pt-BR','<p>Residência da ETC localizada ao lado do campus em Bournemouth, com capacidade para até 60 estudantes internacionais; lounge estudantil com TV e jogos, Wi-Fi gratuito, CCTV e equipe no local; quarto com cama, guarda-roupa, cômoda e aquecimento central.</p><p>Apartamentos self-catering de 2 e 3 quartos a poucos minutos a pé da escola, indicados para grupos de amigos ou familiares e também disponíveis para uso exclusivo de um único estudante. A GSE não publica preço para esta opção: o valor é informado sob consulta conforme o período da viagem. A escola também intermedia hotéis de 3, 4 e 5 estrelas, igualmente sob consulta. Transfer de aeroporto ida e volta €50, mais €15 por acompanhante no mesmo voo; chegadas entre 22h e 6h têm transfer obrigatório de €30 somente ida. Seguro médico e de viagem internacional €12 por semana. Taxa de inscrição da escola €50 e material do curso €35 (cobradas no curso, não na acomodação). Fonte: GSE Adult, Family Programmes and 50 plus Courses and Accommodation Price List 2026 (english-malta.com).</p>','["Perto da Escola", "Lounge Social", "TV", "Wi-Fi", "CCTV", "Equipe no Local", "Aquecimento", "Ideal para famílias e grupos que preferem privacidade e cozinhar"]'::jsonb,'["Menos indicado para quem busca imersão com família local"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'1545ba6a-1aad-5804-8f03-9515c842937a','Apartamento — quarto compartilhado, banheiro privativo, sem refeições','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,0.0,0);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_pid);
  end if;

  select tenant_id into v_tid from campus where id='1545ba6a-1aad-5804-8f03-9515c842937a';
  select id into v_pid from product where campus_id='1545ba6a-1aad-5804-8f03-9515c842937a' and kind='accommodation' and attributes->>'slug'='gse-st-julian-malta-homestay-shared-half-board' and coalesce(attributes->>'category','')='' and archived_at is null;
  if v_pid is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes)
      values (v_tid,'1545ba6a-1aad-5804-8f03-9515c842937a','accommodation','Casa de família — quarto compartilhado, banheiro compartilhado, meia pensão','supplier','quotable','active','week',1,52,'{"seed": "planilha-2026-09", "slug": "gse-st-julian-malta-homestay-shared-half-board", "category": null, "availability_status": "Pré-confirmado", "link": "https://english-malta.com/accommodation/host-families-homestay-malta/", "supplements": {"high_season_supplement": "45", "high_season_period": "26/jun a 30/ago/2026", "low_season_period": "fora de 26/jun a 30/ago/2026 (preço base)", "private_bathroom_supplement": "80", "special_diet_supplement": "70", "extra_night_fee": "30"}}'::jsonb) returning id into v_pid;
    insert into accommodation_detail (product_id, accommodation_type, room_type, bathroom_type, meal_plan) values (v_pid,'homestay','shared_2','shared','half_board');
    insert into product_content (product_id, locale, description_html, highlights, exclusions) values (v_pid,'pt-BR','<p>Família anfitriã da LSI Boston, cuidadosamente selecionada para oferecer um ambiente acolhedor e seguro; inclui refeições diárias e serviço de lavanderia; ótima oportunidade para praticar o idioma no dia a dia e vivenciar a cultura local.</p><p>Suplementos e condições: Suplemento de alta temporada: EUR 45/semana (26/jun a 30/ago/2026); Suplemento banheiro privativo: EUR 80/semana; Suplemento dieta especial: EUR 70/semana; Noite extra: EUR 30.</p><p>Alta temporada de 26/jun a 30/ago/2026: acrescente €45 por semana ao valor base; fora desse período vale o preço base. Banheiro privativo €80 por semana e dieta especial €70 por semana. Noite extra: €30 em quarto compartilhado e €38 em quarto individual na baixa temporada, €36 e €60 na alta. As famílias ficam de 5 a 20 minutos a pé da escola ou a um curto trajeto de ônibus. Transfer de aeroporto ida e volta €50, mais €15 por acompanhante no mesmo voo; chegadas entre 22h e 6h têm transfer obrigatório de €30 somente ida. Seguro médico e de viagem internacional €12 por semana. Taxa de inscrição da escola €50 e material do curso €35 (cobradas no curso, não na acomodação). Fonte: GSE Adult, Family Programmes and 50 plus Courses and Accommodation Price List 2026 (english-malta.com).</p>','["Anfitriões Licenciados", "Refeições Incluídas", "Serviço de Lavanderia", "Ideal para amigos que viajam juntos e querem imersão cultural"]'::jsonb,'["Menos indicado para quem busca total independência"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'1545ba6a-1aad-5804-8f03-9515c842937a','Casa de família — quarto compartilhado, banheiro compartilhado, meia pensão','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,209.0,0);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,8,198.0,1);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,24,198.0,2);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_pid);
  end if;

  select tenant_id into v_tid from campus where id='1545ba6a-1aad-5804-8f03-9515c842937a';
  select id into v_pid from product where campus_id='1545ba6a-1aad-5804-8f03-9515c842937a' and kind='accommodation' and attributes->>'slug'='gse-st-julian-malta-homestay-single-half-board' and coalesce(attributes->>'category','')='' and archived_at is null;
  if v_pid is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes)
      values (v_tid,'1545ba6a-1aad-5804-8f03-9515c842937a','accommodation','Casa de família — quarto individual, banheiro compartilhado, meia pensão','supplier','quotable','active','week',1,52,'{"seed": "planilha-2026-09", "slug": "gse-st-julian-malta-homestay-single-half-board", "category": null, "availability_status": "Pré-confirmado", "link": "https://english-malta.com/accommodation/host-families-homestay-malta/", "supplements": {"high_season_supplement": "115", "high_season_period": "26/jun a 30/ago/2026", "low_season_period": "fora de 26/jun a 30/ago/2026 (preço base)", "private_bathroom_supplement": "80", "special_diet_supplement": "70", "extra_night_fee": "38"}}'::jsonb) returning id into v_pid;
    insert into accommodation_detail (product_id, accommodation_type, room_type, bathroom_type, meal_plan) values (v_pid,'homestay','private','shared','half_board');
    insert into product_content (product_id, locale, description_html, highlights, exclusions) values (v_pid,'pt-BR','<p>Residência estudantil da LSI New York, centralmente localizada, que equilibra independência e vida social; conta com áreas comuns para conviver com estudantes de várias nacionalidades, limpeza regular e lavanderia.</p><p>Suplementos e condições: Suplemento de alta temporada: EUR 115/semana (26/jun a 30/ago/2026); Suplemento banheiro privativo: EUR 80/semana; Suplemento dieta especial: EUR 70/semana; Noite extra: EUR 38.</p><p>Alta temporada de 26/jun a 30/ago/2026: acrescente €115 por semana ao valor base; fora desse período vale o preço base. Banheiro privativo €80 por semana e dieta especial €70 por semana. Noite extra: €30 em quarto compartilhado e €38 em quarto individual na baixa temporada, €36 e €60 na alta. As famílias ficam de 5 a 20 minutos a pé da escola ou a um curto trajeto de ônibus. Transfer de aeroporto ida e volta €50, mais €15 por acompanhante no mesmo voo; chegadas entre 22h e 6h têm transfer obrigatório de €30 somente ida. Seguro médico e de viagem internacional €12 por semana. Taxa de inscrição da escola €50 e material do curso €35 (cobradas no curso, não na acomodação). Fonte: GSE Adult, Family Programmes and 50 plus Courses and Accommodation Price List 2026 (english-malta.com).</p>','["Localização Central", "Áreas Comuns", "Ambiente Internacional", "Limpeza Regular", "Serviço de Lavanderia", "Ideal para quem busca imersão cultural com família local"]'::jsonb,'["Menos indicado para quem busca total independência"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'1545ba6a-1aad-5804-8f03-9515c842937a','Casa de família — quarto individual, banheiro compartilhado, meia pensão','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,300.0,0);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,8,265.0,1);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,24,265.0,2);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_pid);
  end if;

  select tenant_id into v_tid from campus where id='1545ba6a-1aad-5804-8f03-9515c842937a';
  select id into v_pid from product where campus_id='1545ba6a-1aad-5804-8f03-9515c842937a' and kind='accommodation' and attributes->>'slug'='gse-st-julian-malta-residence-shared-breakfast' and coalesce(attributes->>'category','')='' and archived_at is null;
  if v_pid is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes)
      values (v_tid,'1545ba6a-1aad-5804-8f03-9515c842937a','accommodation','Residência estudantil — quarto compartilhado, banheiro compartilhado, café da manhã','supplier','quotable','active','week',1,52,'{"seed": "planilha-2026-09", "slug": "gse-st-julian-malta-residence-shared-breakfast", "category": null, "availability_status": "Requer confirmação", "link": "https://english-malta.com/accommodation/the-gateway-school-student-residence/", "supplements": {"high_season_supplement": "60", "high_season_period": "26/jun a 30/ago/2026", "low_season_period": "fora de 26/jun a 30/ago/2026 (preço base)", "extra_night_fee": "30", "damage_deposit": "50"}}'::jsonb) returning id into v_pid;
    insert into accommodation_detail (product_id, accommodation_type, room_type, bathroom_type, meal_plan) values (v_pid,'residence','shared_2','shared','breakfast');
    insert into product_content (product_id, locale, description_html, highlights, exclusions) values (v_pid,'pt-BR','<p>Quarto compartilhado (twin ou triplo, conforme disponibilidade). Banheiro compartilhado (limpo diariamente). Regime de café da manhã incluído (buffet). Inclui: ar-condicionado/aquecimento, Wi-Fi e uso da cozinha comunitária. Não inclui: almoço e jantar.</p><p>Suplementos e condições: Suplemento de alta temporada: EUR 60/semana (26/jun a 30/ago/2026); Noite extra: EUR 30; Depósito caução (reembolsável): EUR 50.</p><p>Alta temporada de 26/jun a 30/ago/2026: acrescente €60 por semana ao valor base; fora desse período vale o preço base. Noite extra na residência: €30 por noite em quarto compartilhado e €55 em quarto individual na baixa temporada, €37 e €65 na alta. Caução de €50 em dinheiro cobrada no check-in e devolvida no check-out. Ar-condicionado funciona com moedas no verão, Wi-Fi é gratuito, os banheiros são compartilhados por cerca de 4 alunos no inverno e 6 no verão, os quartos são limpos em dias alternados e roupa de cama e toalhas trocadas uma vez por semana. Transfer de aeroporto ida e volta €50, mais €15 por acompanhante no mesmo voo; chegadas entre 22h e 6h têm transfer obrigatório de €30 somente ida. Seguro médico e de viagem internacional €12 por semana. Taxa de inscrição da escola €50 e material do curso €35 (cobradas no curso, não na acomodação). Fonte: GSE Adult, Family Programmes and 50 plus Courses and Accommodation Price List 2026 (english-malta.com).</p>','["Residência da Gateway School of English (GSE) ao lado da escola em St. Julian''s/San Gwann, a apenas 2-3 minutos a pé da sala de aula; quartos totalmente climatizados (ar-condicionado e aquecimento), Wi-Fi gratuito em toda a propriedade, cozinha comunitária moderna para preparo de refeições, área de convívio e pátio; café da manhã em buffet incluído.", "Ideal para quem viaja em grupo e busca ambiente internacional"]'::jsonb,'["Menos indicado para quem exige banheiro privativo"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'1545ba6a-1aad-5804-8f03-9515c842937a','Residência estudantil — quarto compartilhado, banheiro compartilhado, café da manhã','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,191.0,0);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,8,180.0,1);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,24,180.0,2);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_pid);
  end if;
end $$;