do $$ declare v_pid uuid; v_tid uuid; v_tpl uuid; v_fee uuid; begin

  select tenant_id into v_tid from campus where id='1e52299a-af6a-5cad-a327-08cd9a10b062';
  select id into v_pid from product where campus_id='1e52299a-af6a-5cad-a327-08cd9a10b062' and kind='accommodation' and attributes->>'slug'='etc-international-college-bournemouth-uk-homestay-executive-single-half-board' and coalesce(attributes->>'category','')='Executive' and archived_at is null;
  if v_pid is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes)
      values (v_tid,'1e52299a-af6a-5cad-a327-08cd9a10b062','accommodation','Casa de família Executive — quarto individual, banheiro privativo, meia pensão','supplier','quotable','active','week',1,52,'{"seed": "planilha-2026-09", "slug": "etc-international-college-bournemouth-uk-homestay-executive-single-half-board", "category": "Executive", "availability_status": "Pré-confirmado", "link": "https://etc-inter.net/homestay/", "supplements": {"high_season_supplement": "15", "high_season_period": "24/mai a 15/ago/2026", "low_season_period": "4/jan a 23/mai/2026 e 16/ago/2026 a 3/jan/2027 (preço base)", "special_diet_supplement": "30", "extra_night_fee": "50", "other_supplement_fee": "50"}}'::jsonb) returning id into v_pid;
    insert into accommodation_detail (product_id, accommodation_type, room_type, bathroom_type, meal_plan) values (v_pid,'homestay','private','private','half_board');
    insert into product_content (product_id, locale, description_html, highlights, exclusions) values (v_pid,'pt-BR','<p>Quarto individual (privativo). Banheiro privativo (en-suite). Regime de meia pensão: café da manhã e jantar de segunda a sexta; pensão completa nos fins de semana. Inclui: roupa de cama, toalhas, limpeza semanal e acesso à internet/facilidades de TI. Categoria premium dentro da opção homestay.</p><p>Suplementos e condições: Suplemento de alta temporada: GBP 15/semana (24/mai a 15/ago/2026); Suplemento dieta especial: GBP 30/semana; Noite extra: GBP 50; Outro suplemento: GBP 50.</p><p>O preço base é o de baixa temporada (4/jan a 23/mai/2026 e 16/ago/2026 a 3/jan/2027); na alta temporada (24/mai a 15/ago/2026) acrescente £15 por semana. Taxa de reserva da acomodação £40, cobrada uma única vez. Noite extra £50 na baixa temporada e £55 na alta. Taxa de dieta especial £30 por semana (cobre intolerância à lactose, vegetariano e sem glúten). Suplemento de Natal £50 por semana para quem fica entre 20/12/2026 e 3/1/2027 (não se aplica na alta temporada). Taxa para manter o quarto reservado durante viagens £80 por semana. Taxa de cancelamento ou troca de família £100. Quarto individual para 16 e 17 anos custa £205 por semana na baixa e £250 na alta temporada. Estadias de domingo a domingo. Fonte: ETC Adult Dates and Fees 2026 (01/09/2025).</p>','["Homestay executivo com família anfitriã britânica selecionada pela ETC; inclui acesso a internet e facilidades de TI para quem precisa estudar ou trabalhar remotamente; ambiente tranquilo e privado.", "Ideal para adultos 18+ que querem homestay com banheiro privativo"]'::jsonb,'["Menos indicado para quem tem orçamento reduzido"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'1e52299a-af6a-5cad-a327-08cd9a10b062','Casa de família Executive — quarto individual, banheiro privativo, meia pensão','duration','flexible','week','GBP',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,295.0,0);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_pid);
    insert into fee (tenant_id, campus_id, name, fee_type, charge_basis, amount, currency, is_mandatory, is_refundable) values (v_tid,'1e52299a-af6a-5cad-a327-08cd9a10b062','Taxa de colocação em acomodação','placement','once_per_item',40.0,'GBP',true,false) returning id into v_fee;
    insert into fee_product (fee_id, product_id) values (v_fee, v_pid);
  end if;

  select tenant_id into v_tid from campus where id='1e52299a-af6a-5cad-a327-08cd9a10b062';
  select id into v_pid from product where campus_id='1e52299a-af6a-5cad-a327-08cd9a10b062' and kind='accommodation' and attributes->>'slug'='etc-international-college-bournemouth-uk-homestay-shared-half-board' and coalesce(attributes->>'category','')='' and archived_at is null;
  if v_pid is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes)
      values (v_tid,'1e52299a-af6a-5cad-a327-08cd9a10b062','accommodation','Casa de família — quarto compartilhado, banheiro compartilhado, meia pensão','supplier','quotable','active','week',1,52,'{"seed": "planilha-2026-09", "slug": "etc-international-college-bournemouth-uk-homestay-shared-half-board", "category": null, "availability_status": "Pré-confirmado", "link": "https://etc-inter.net/homestay/", "supplements": {"high_season_supplement": "30", "high_season_period": "24/mai a 15/ago/2026", "low_season_period": "4/jan a 23/mai/2026 e 16/ago/2026 a 3/jan/2027 (preço base)", "special_diet_supplement": "30", "extra_night_fee": "35", "other_supplement_fee": "50"}}'::jsonb) returning id into v_pid;
    insert into accommodation_detail (product_id, accommodation_type, room_type, bathroom_type, meal_plan) values (v_pid,'homestay','shared_2','shared','half_board');
    insert into product_content (product_id, locale, description_html, highlights, exclusions) values (v_pid,'pt-BR','<p>Família anfitriã da LSI Boston, cuidadosamente selecionada para oferecer um ambiente acolhedor e seguro; inclui refeições diárias e serviço de lavanderia; ótima oportunidade para praticar o idioma no dia a dia e vivenciar a cultura local.</p><p>Suplementos e condições: Suplemento de alta temporada: GBP 30/semana (24/mai a 15/ago/2026); Suplemento dieta especial: GBP 30/semana; Noite extra: GBP 35; Outro suplemento: GBP 50.</p><p>O preço base é o de baixa temporada (4/jan a 23/mai/2026 e 16/ago/2026 a 3/jan/2027); na alta temporada (24/mai a 15/ago/2026) acrescente £30 por semana. Taxa de reserva da acomodação £40, cobrada uma única vez. Noite extra £35 na baixa temporada e £45 na alta. Taxa de dieta especial £30 por semana (cobre intolerância à lactose, vegetariano e sem glúten). Suplemento de Natal £50 por semana para quem fica entre 20/12/2026 e 3/1/2027 (não se aplica na alta temporada). Taxa para manter o quarto reservado durante viagens £80 por semana. Taxa de cancelamento ou troca de família £100. Quarto individual para 16 e 17 anos custa £205 por semana na baixa e £250 na alta temporada. Estadias de domingo a domingo. Fonte: ETC Adult Dates and Fees 2026 (01/09/2025).</p>','["Anfitriões Licenciados", "Refeições Incluídas", "Serviço de Lavanderia", "Ideal para amigos que viajam juntos e querem imersão cultural"]'::jsonb,'["Menos indicado para quem busca total privacidade"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'1e52299a-af6a-5cad-a327-08cd9a10b062','Casa de família — quarto compartilhado, banheiro compartilhado, meia pensão','duration','flexible','week','GBP',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,185.0,0);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_pid);
    insert into fee (tenant_id, campus_id, name, fee_type, charge_basis, amount, currency, is_mandatory, is_refundable) values (v_tid,'1e52299a-af6a-5cad-a327-08cd9a10b062','Taxa de colocação em acomodação','placement','once_per_item',40.0,'GBP',true,false) returning id into v_fee;
    insert into fee_product (fee_id, product_id) values (v_fee, v_pid);
  end if;

  select tenant_id into v_tid from campus where id='1e52299a-af6a-5cad-a327-08cd9a10b062';
  select id into v_pid from product where campus_id='1e52299a-af6a-5cad-a327-08cd9a10b062' and kind='accommodation' and attributes->>'slug'='etc-international-college-bournemouth-uk-homestay-single-half-board' and coalesce(attributes->>'category','')='' and archived_at is null;
  if v_pid is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes)
      values (v_tid,'1e52299a-af6a-5cad-a327-08cd9a10b062','accommodation','Casa de família — quarto individual, banheiro compartilhado, meia pensão','supplier','quotable','active','week',1,52,'{"seed": "planilha-2026-09", "slug": "etc-international-college-bournemouth-uk-homestay-single-half-board", "category": null, "availability_status": "Pré-confirmado", "link": "https://etc-inter.net/homestay/", "supplements": {"high_season_supplement": "40", "high_season_period": "24/mai a 15/ago/2026", "low_season_period": "4/jan a 23/mai/2026 e 16/ago/2026 a 3/jan/2027 (preço base)", "special_diet_supplement": "30", "extra_night_fee": "35", "other_supplement_fee": "50"}}'::jsonb) returning id into v_pid;
    insert into accommodation_detail (product_id, accommodation_type, room_type, bathroom_type, meal_plan) values (v_pid,'homestay','private','shared','half_board');
    insert into product_content (product_id, locale, description_html, highlights, exclusions) values (v_pid,'pt-BR','<p>Família anfitriã da LSI New York, cuidadosamente selecionada para oferecer um ambiente acolhedor e seguro; ótima oportunidade para praticar o idioma no dia a dia e vivenciar a cultura local.</p><p>Suplementos e condições: Suplemento de alta temporada: GBP 40/semana (24/mai a 15/ago/2026); Suplemento dieta especial: GBP 30/semana; Noite extra: GBP 35; Outro suplemento: GBP 50.</p><p>O preço base é o de baixa temporada (4/jan a 23/mai/2026 e 16/ago/2026 a 3/jan/2027); na alta temporada (24/mai a 15/ago/2026) acrescente £40 por semana. Taxa de reserva da acomodação £40, cobrada uma única vez. Noite extra £35 na baixa temporada e £45 na alta. Taxa de dieta especial £30 por semana (cobre intolerância à lactose, vegetariano e sem glúten). Suplemento de Natal £50 por semana para quem fica entre 20/12/2026 e 3/1/2027 (não se aplica na alta temporada). Taxa para manter o quarto reservado durante viagens £80 por semana. Taxa de cancelamento ou troca de família £100. Quarto individual para 16 e 17 anos custa £205 por semana na baixa e £250 na alta temporada. Estadias de domingo a domingo. Fonte: ETC Adult Dates and Fees 2026 (01/09/2025).</p>','["Anfitriões Licenciados", "Ideal para quem quer vivenciar a cultura britânica e praticar inglês em casa"]'::jsonb,'["Menos indicado para quem busca banheiro privativo garantido"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'1e52299a-af6a-5cad-a327-08cd9a10b062','Casa de família — quarto individual, banheiro compartilhado, meia pensão','duration','flexible','week','GBP',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,190.0,0);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_pid);
    insert into fee (tenant_id, campus_id, name, fee_type, charge_basis, amount, currency, is_mandatory, is_refundable) values (v_tid,'1e52299a-af6a-5cad-a327-08cd9a10b062','Taxa de colocação em acomodação','placement','once_per_item',40.0,'GBP',true,false) returning id into v_fee;
    insert into fee_product (fee_id, product_id) values (v_fee, v_pid);
  end if;

  select tenant_id into v_tid from campus where id='1e52299a-af6a-5cad-a327-08cd9a10b062';
  select id into v_pid from product where campus_id='1e52299a-af6a-5cad-a327-08cd9a10b062' and kind='accommodation' and attributes->>'slug'='etc-international-college-bournemouth-uk-residence-shared-none' and coalesce(attributes->>'category','')='' and archived_at is null;
  if v_pid is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes)
      values (v_tid,'1e52299a-af6a-5cad-a327-08cd9a10b062','accommodation','Residência estudantil — quarto compartilhado, banheiro privativo, sem refeições','supplier','quotable','active','week',1,52,'{"seed": "planilha-2026-09", "slug": "etc-international-college-bournemouth-uk-residence-shared-none", "category": null, "availability_status": "Requer confirmação", "link": "https://etc-inter.net/residence/", "supplements": {"high_season_period": "não publicado", "low_season_period": "não publicado", "damage_deposit": "200"}}'::jsonb) returning id into v_pid;
    insert into accommodation_detail (product_id, accommodation_type, room_type, bathroom_type, meal_plan) values (v_pid,'residence','shared_2','private','none');
    insert into product_content (product_id, locale, description_html, highlights, exclusions) values (v_pid,'pt-BR','<p>Quarto compartilhado (tipo twin, com outro estudante). Banheiro privativo (en-suite: chuveiro, pia e vaso sanitário). Sem plano de refeições incluído por padrão (opção de café da manhã disponível como upgrade). Inclui: roupa de cama, serviço de lavanderia, limpeza semanal do quarto e Wi-Fi. Não inclui: refeições. Depósito de caução (cartão de crédito) exigido na chegada.</p><p>Suplementos e condições: Depósito caução (reembolsável): GBP 200.</p><p>A escola não publica ajuste sazonal nem suplementos para a residência na tabela Adult Dates and Fees 2026 — o valor final é confirmado no orçamento (price calculator) da ETC. É exigida uma autorização de cartão de crédito de £200 na chegada como caução (ou alternativa combinada com a escola) e o pagamento antecipado de uma semana de acomodação no ato da reserva. Estadias de sábado a sábado ou de domingo a domingo. Quartos com banheiro privativo, roupa de cama, limpeza semanal e Wi-Fi inclusos; no verão a escola também usa residências parceiras (apartamentos self-catering de 5 a 9 quartos, todos com banheiro privativo). Transfer privativo do aeroporto, somente ida, para 1 pessoa: Heathrow £180, Gatwick £200, Luton £220, Stansted £270, Bournemouth £45, Southampton £100 e Londres centro £260; check-in assistido £50 e espera £30 por hora. Fonte: etc-inter.net/residence e ETC Adult Dates and Fees 2026.</p>','["Residência da ETC localizada ao lado do campus em Bournemouth, com capacidade para até 60 estudantes internacionais; lounge estudantil com TV e jogos, Wi-Fi gratuito, CCTV e equipe no local; quarto com cama, guarda-roupa, cômoda e aquecimento central.", "Ideal para quem viaja com amigos e quer dividir custos com conforto"]'::jsonb,'["Menos indicado para quem prefere imersão com família local"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'1e52299a-af6a-5cad-a327-08cd9a10b062','Residência estudantil — quarto compartilhado, banheiro privativo, sem refeições','duration','flexible','week','GBP',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,155.0,0);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_pid);
  end if;

  select tenant_id into v_tid from campus where id='1e52299a-af6a-5cad-a327-08cd9a10b062';
  select id into v_pid from product where campus_id='1e52299a-af6a-5cad-a327-08cd9a10b062' and kind='accommodation' and attributes->>'slug'='etc-international-college-bournemouth-uk-residence-single-none' and coalesce(attributes->>'category','')='' and archived_at is null;
  if v_pid is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes)
      values (v_tid,'1e52299a-af6a-5cad-a327-08cd9a10b062','accommodation','Residência estudantil — quarto individual, banheiro privativo, sem refeições','supplier','quotable','active','week',1,52,'{"seed": "planilha-2026-09", "slug": "etc-international-college-bournemouth-uk-residence-single-none", "category": null, "availability_status": "Requer confirmação", "link": "https://etc-inter.net/residence/", "supplements": {"high_season_period": "não publicado", "low_season_period": "não publicado", "damage_deposit": "200"}}'::jsonb) returning id into v_pid;
    insert into accommodation_detail (product_id, accommodation_type, room_type, bathroom_type, meal_plan) values (v_pid,'residence','private','private','none');
    insert into product_content (product_id, locale, description_html, highlights, exclusions) values (v_pid,'pt-BR','<p>Quarto individual (privativo). Banheiro privativo (en-suite: chuveiro, pia e vaso sanitário). Sem plano de refeições incluído por padrão (opção de café da manhã disponível como upgrade). Inclui: roupa de cama, serviço de lavanderia, limpeza semanal do quarto e Wi-Fi. Não inclui: refeições. Depósito de caução (cartão de crédito) exigido na chegada.</p><p>Suplementos e condições: Depósito caução (reembolsável): GBP 200.</p><p>A escola não publica ajuste sazonal nem suplementos para a residência na tabela Adult Dates and Fees 2026 — o valor final é confirmado no orçamento (price calculator) da ETC. É exigida uma autorização de cartão de crédito de £200 na chegada como caução (ou alternativa combinada com a escola) e o pagamento antecipado de uma semana de acomodação no ato da reserva. Estadias de sábado a sábado ou de domingo a domingo. Quartos com banheiro privativo, roupa de cama, limpeza semanal e Wi-Fi inclusos; no verão a escola também usa residências parceiras (apartamentos self-catering de 5 a 9 quartos, todos com banheiro privativo). Transfer privativo do aeroporto, somente ida, para 1 pessoa: Heathrow £180, Gatwick £200, Luton £220, Stansted £270, Bournemouth £45, Southampton £100 e Londres centro £260; check-in assistido £50 e espera £30 por hora. Fonte: etc-inter.net/residence e ETC Adult Dates and Fees 2026.</p>','["Residência da ETC localizada ao lado do campus em Bournemouth, com capacidade para até 60 estudantes internacionais; lounge estudantil com TV e jogos, Wi-Fi gratuito, CCTV e equipe no local; quarto com cama, guarda-roupa, cômoda e aquecimento central.", "Ideal para quem quer independência ao lado da escola, com banheiro privativo"]'::jsonb,'["Menos indicado para quem prefere imersão com família local"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'1e52299a-af6a-5cad-a327-08cd9a10b062','Residência estudantil — quarto individual, banheiro privativo, sem refeições','duration','flexible','week','GBP',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,220.0,0);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_pid);
  end if;
end $$;