do $$ declare v_pid uuid; v_tid uuid; v_tpl uuid; v_fee uuid; begin

  select tenant_id into v_tid from campus where id='98d1b1fd-34af-556e-ba8a-ffe07efb5c51';
  select id into v_pid from product where campus_id='98d1b1fd-34af-556e-ba8a-ffe07efb5c51' and kind='accommodation' and attributes->>'slug'='bels-gozo-malta-apartment-shared-none' and coalesce(attributes->>'category','')='' and archived_at is null;
  if v_pid is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes)
      values (v_tid,'98d1b1fd-34af-556e-ba8a-ffe07efb5c51','accommodation','Apartamento — quarto compartilhado, banheiro compartilhado, sem refeições','supplier','quotable','active','week',1,52,'{"seed": "planilha-2026-09", "slug": "bels-gozo-malta-apartment-shared-none", "category": null, "availability_status": "Requer confirmação", "link": "https://belsmalta.com/accommodation/gozo/self-catering-apartments/", "supplements": {"high_season_supplement": "30", "high_season_period": "28/jun a 29/ago", "low_season_discount": "30", "low_season_period": "3/jan a 28/fev e 1/nov a 31/dez", "private_bathroom_supplement": "70", "extra_night_fee": "70", "damage_deposit": "100", "other_supplement_fee": "10.5"}}'::jsonb) returning id into v_pid;
    insert into accommodation_detail (product_id, accommodation_type, room_type, bathroom_type, meal_plan) values (v_pid,'shared_apartment','shared_2','shared','none');
    insert into product_content (product_id, locale, description_html, highlights, exclusions) values (v_pid,'pt-BR','<p>Residência moderna no centro de Victoria (Gozo), a poucos minutos a pé da estação de ônibus principal; cozinha totalmente equipada, ar-condicionado/aquecimento, máquina de lavar e Wi-Fi de alta velocidade; áreas comuns para convívio com outros estudantes; limpeza semanal com troca de roupa de cama e toalhas; suporte 24/7 da equipe da escola.</p><p>Suplementos e condições: Suplemento de alta temporada: EUR 30/semana (28/jun a 29/ago); Desconto de baixa temporada: EUR 30/semana (3/jan a 28/fev e 1/nov a 31/dez); Suplemento banheiro privativo: EUR 70/semana; Noite extra: EUR 70; Depósito caução (reembolsável): EUR 100; Outro suplemento: EUR 10.5.</p><p>Ajuste sazonal da acomodação, por semana: alta temporada 28/jun a 29/ago +€30; baixa temporada 3/jan a 28/fev e 1/nov a 31/dez -€30; média temporada 1/mar a 27/jun e 30/ago a 31/out sem ajuste. O ajuste não se aplica a reservas de 12+ semanas. Taxa obrigatória: Eco Tax (18+) €10,50 por semana, máximo €22,50 por estadia. Transfer de chegada com check-in €60 (obrigatório) e transfer de saída €60 (opcional); pessoa adicional no mesmo transfer €10. Alteração de reserva €30. Opcionais por semana: banheiro privativo €70 (mediante solicitação, em quarto individual); seguro €17. Noite extra €70 por noite. Depósito caução reembolsável de €100 em dinheiro, recolhido no primeiro dia de aula para quem fica em residência BELS e devolvido no último dia se não houver danos. Semanas calculadas em estadias de 7 noites (check-in sábado/domingo, entrada 15:00 e saída 10:00); noites extras para chegada antecipada ou saída tardia são cobradas à parte. Fonte: BELS Malta Price List 2026 (atualização fev/2026).</p>','["Cozinha Equipada", "Ar-condicionado", "Aquecimento", "Máquina de Lavar", "Wi-Fi", "Áreas Comuns", "Limpeza Semanal", "Troca de Roupa de Cama e Toalhas", "Suporte 24/7", "Ideal para grupos e famílias que preferem independência e cozinhar"]'::jsonb,'["Menos indicado para quem busca imersão com família local"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'98d1b1fd-34af-556e-ba8a-ffe07efb5c51','Apartamento — quarto compartilhado, banheiro compartilhado, sem refeições','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,225.0,0);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_pid);
  end if;

  select tenant_id into v_tid from campus where id='98d1b1fd-34af-556e-ba8a-ffe07efb5c51';
  select id into v_pid from product where campus_id='98d1b1fd-34af-556e-ba8a-ffe07efb5c51' and kind='accommodation' and attributes->>'slug'='bels-gozo-malta-homestay-shared-half-board' and coalesce(attributes->>'category','')='' and archived_at is null;
  if v_pid is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes)
      values (v_tid,'98d1b1fd-34af-556e-ba8a-ffe07efb5c51','accommodation','Casa de família — quarto compartilhado, banheiro compartilhado, meia pensão','supplier','quotable','active','week',1,52,'{"seed": "planilha-2026-09", "slug": "bels-gozo-malta-homestay-shared-half-board", "category": null, "availability_status": "Pré-confirmado", "link": "https://belsmalta.com/accommodation/gozo/home-stay/", "supplements": {"high_season_supplement": "30", "high_season_period": "28/jun a 29/ago", "low_season_discount": "30", "low_season_period": "3/jan a 28/fev e 1/nov a 31/dez", "private_bathroom_supplement": "70", "special_diet_supplement": "70", "extra_night_fee": "70", "other_supplement_fee": "10.5"}}'::jsonb) returning id into v_pid;
    insert into accommodation_detail (product_id, accommodation_type, room_type, bathroom_type, meal_plan) values (v_pid,'homestay','shared_2','shared','half_board');
    insert into product_content (product_id, locale, description_html, highlights, exclusions) values (v_pid,'pt-BR','<p>Residência estudantil da LSI Auckland, que equilibra independência e vida social; conta com áreas comuns para conviver com estudantes de várias nacionalidades, limpeza regular e lavanderia.</p><p>Suplementos e condições: Suplemento de alta temporada: EUR 30/semana (28/jun a 29/ago); Desconto de baixa temporada: EUR 30/semana (3/jan a 28/fev e 1/nov a 31/dez); Suplemento banheiro privativo: EUR 70/semana; Suplemento dieta especial: EUR 70/semana; Noite extra: EUR 70; Outro suplemento: EUR 10.5.</p><p>Ajuste sazonal da acomodação, por semana: alta temporada 28/jun a 29/ago +€30; baixa temporada 3/jan a 28/fev e 1/nov a 31/dez -€30; média temporada 1/mar a 27/jun e 30/ago a 31/out sem ajuste. O ajuste não se aplica a reservas de 12+ semanas. Taxa obrigatória: Eco Tax (18+) €10,50 por semana, máximo €22,50 por estadia. Transfer de chegada com check-in €60 (obrigatório) e transfer de saída €60 (opcional); pessoa adicional no mesmo transfer €10. Alteração de reserva €30. Opcionais por semana: banheiro privativo €70 (mediante solicitação, em quarto individual); dieta especial €70 (não cobrada para dietas vegetarianas); seguro €17. Noite extra €70 por noite. Semanas calculadas em estadias de 7 noites (check-in sábado/domingo, entrada 15:00 e saída 10:00); noites extras para chegada antecipada ou saída tardia são cobradas à parte. Fonte: BELS Malta Price List 2026 (atualização fev/2026).</p>','["Áreas Comuns", "Ambiente Internacional", "Limpeza Regular", "Serviço de Lavanderia", "Ideal para amigos que viajam juntos e querem imersão cultural"]'::jsonb,'["Menos indicado para quem busca total independência"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'98d1b1fd-34af-556e-ba8a-ffe07efb5c51','Casa de família — quarto compartilhado, banheiro compartilhado, meia pensão','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,300.0,0);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_pid);
  end if;

  select tenant_id into v_tid from campus where id='98d1b1fd-34af-556e-ba8a-ffe07efb5c51';
  select id into v_pid from product where campus_id='98d1b1fd-34af-556e-ba8a-ffe07efb5c51' and kind='accommodation' and attributes->>'slug'='bels-gozo-malta-homestay-single-half-board' and coalesce(attributes->>'category','')='' and archived_at is null;
  if v_pid is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes)
      values (v_tid,'98d1b1fd-34af-556e-ba8a-ffe07efb5c51','accommodation','Casa de família — quarto individual, banheiro compartilhado, meia pensão','supplier','quotable','active','week',1,52,'{"seed": "planilha-2026-09", "slug": "bels-gozo-malta-homestay-single-half-board", "category": null, "availability_status": "Pré-confirmado", "link": "https://belsmalta.com/accommodation/gozo/home-stay/", "supplements": {"high_season_supplement": "30", "high_season_period": "28/jun a 29/ago", "low_season_discount": "30", "low_season_period": "3/jan a 28/fev e 1/nov a 31/dez", "private_bathroom_supplement": "70", "special_diet_supplement": "70", "extra_night_fee": "70", "other_supplement_fee": "10.5"}}'::jsonb) returning id into v_pid;
    insert into accommodation_detail (product_id, accommodation_type, room_type, bathroom_type, meal_plan) values (v_pid,'homestay','private','shared','half_board');
    insert into product_content (product_id, locale, description_html, highlights, exclusions) values (v_pid,'pt-BR','<p>Família anfitriã da LSI New York, cuidadosamente selecionada para oferecer um ambiente acolhedor e seguro; ótima oportunidade para praticar o idioma no dia a dia e vivenciar a cultura local.</p><p>Suplementos e condições: Suplemento de alta temporada: EUR 30/semana (28/jun a 29/ago); Desconto de baixa temporada: EUR 30/semana (3/jan a 28/fev e 1/nov a 31/dez); Suplemento banheiro privativo: EUR 70/semana; Suplemento dieta especial: EUR 70/semana; Noite extra: EUR 70; Outro suplemento: EUR 10.5.</p><p>Ajuste sazonal da acomodação, por semana: alta temporada 28/jun a 29/ago +€30; baixa temporada 3/jan a 28/fev e 1/nov a 31/dez -€30; média temporada 1/mar a 27/jun e 30/ago a 31/out sem ajuste. O ajuste não se aplica a reservas de 12+ semanas. Taxa obrigatória: Eco Tax (18+) €10,50 por semana, máximo €22,50 por estadia. Transfer de chegada com check-in €60 (obrigatório) e transfer de saída €60 (opcional); pessoa adicional no mesmo transfer €10. Alteração de reserva €30. Opcionais por semana: banheiro privativo €70 (mediante solicitação, em quarto individual); dieta especial €70 (não cobrada para dietas vegetarianas); seguro €17. Noite extra €70 por noite. Semanas calculadas em estadias de 7 noites (check-in sábado/domingo, entrada 15:00 e saída 10:00); noites extras para chegada antecipada ou saída tardia são cobradas à parte. Fonte: BELS Malta Price List 2026 (atualização fev/2026).</p>','["Anfitriões Licenciados", "Ideal para quem busca imersão cultural e rotina em família gozitana"]'::jsonb,'["Menos indicado para quem busca total independência ou horários de refeição flexíveis"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'98d1b1fd-34af-556e-ba8a-ffe07efb5c51','Casa de família — quarto individual, banheiro compartilhado, meia pensão','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,390.0,0);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_pid);
  end if;

  select tenant_id into v_tid from campus where id='98d1b1fd-34af-556e-ba8a-ffe07efb5c51';
  select id into v_pid from product where campus_id='98d1b1fd-34af-556e-ba8a-ffe07efb5c51' and kind='accommodation' and attributes->>'slug'='bels-gozo-malta-residence-shared-none' and coalesce(attributes->>'category','')='' and archived_at is null;
  if v_pid is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes)
      values (v_tid,'98d1b1fd-34af-556e-ba8a-ffe07efb5c51','accommodation','Residência estudantil — quarto compartilhado, banheiro compartilhado, sem refeições','supplier','quotable','active','week',1,52,'{"seed": "planilha-2026-09", "slug": "bels-gozo-malta-residence-shared-none", "category": null, "availability_status": "Requer confirmação", "link": "https://belsmalta.com/accommodation/gozo/bels-superior-residence/", "supplements": {"high_season_supplement": "30", "high_season_period": "28/jun a 29/ago", "low_season_discount": "30", "low_season_period": "3/jan a 28/fev e 1/nov a 31/dez", "private_bathroom_supplement": "70", "extra_night_fee": "70", "damage_deposit": "100", "other_supplement_fee": "10.5"}}'::jsonb) returning id into v_pid;
    insert into accommodation_detail (product_id, accommodation_type, room_type, bathroom_type, meal_plan) values (v_pid,'residence','shared_2','shared','none');
    insert into product_content (product_id, locale, description_html, highlights, exclusions) values (v_pid,'pt-BR','<p>Quarto compartilhado (tipo twin, com outro estudante do mesmo sexo). Banheiro compartilhado (banheiro privativo disponível como upgrade, mediante taxa extra). Sem plano de refeições incluído — acomodação self-catering, com cozinha equipada. Inclui: Wi-Fi, ar-condicionado/aquecimento, máquina de lavar, roupa de cama, toalhas e transporte de chegada do aeroporto. Não inclui: refeições.</p><p>Suplementos e condições: Suplemento de alta temporada: EUR 30/semana (28/jun a 29/ago); Desconto de baixa temporada: EUR 30/semana (3/jan a 28/fev e 1/nov a 31/dez); Suplemento banheiro privativo: EUR 70/semana; Noite extra: EUR 70; Depósito caução (reembolsável): EUR 100; Outro suplemento: EUR 10.5.</p><p>Ajuste sazonal da acomodação, por semana: alta temporada 28/jun a 29/ago +€30; baixa temporada 3/jan a 28/fev e 1/nov a 31/dez -€30; média temporada 1/mar a 27/jun e 30/ago a 31/out sem ajuste. O ajuste não se aplica a reservas de 12+ semanas. Taxa obrigatória: Eco Tax (18+) €10,50 por semana, máximo €22,50 por estadia. Transfer de chegada com check-in €60 (obrigatório) e transfer de saída €60 (opcional); pessoa adicional no mesmo transfer €10. Alteração de reserva €30. Opcionais por semana: banheiro privativo €70 (mediante solicitação, em quarto individual); seguro €17. Noite extra €70 por noite. Depósito caução reembolsável de €100 em dinheiro, recolhido no primeiro dia de aula para quem fica em residência BELS e devolvido no último dia se não houver danos. Semanas calculadas em estadias de 7 noites (check-in sábado/domingo, entrada 15:00 e saída 10:00); noites extras para chegada antecipada ou saída tardia são cobradas à parte. Fonte: BELS Malta Price List 2026 (atualização fev/2026).</p>','["Residência moderna no centro de Victoria (Gozo), a poucos minutos a pé da estação de ônibus principal; cozinha totalmente equipada, ar-condicionado/aquecimento, máquina de lavar e Wi-Fi de alta velocidade; áreas comuns para convívio com outros estudantes; limpeza semanal com troca de roupa de cama e toalhas; suporte 24/7 da equipe da escola.", "Ideal para quem viaja com amigos e quer dividir custos"]'::jsonb,'["Menos indicado para quem precisa de total privacidade"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'98d1b1fd-34af-556e-ba8a-ffe07efb5c51','Residência estudantil — quarto compartilhado, banheiro compartilhado, sem refeições','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,225.0,0);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,8,195.0,1);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,12,165.0,2);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,24,145.0,3);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_pid);
  end if;

  select tenant_id into v_tid from campus where id='98d1b1fd-34af-556e-ba8a-ffe07efb5c51';
  select id into v_pid from product where campus_id='98d1b1fd-34af-556e-ba8a-ffe07efb5c51' and kind='accommodation' and attributes->>'slug'='bels-gozo-malta-residence-single-none' and coalesce(attributes->>'category','')='' and archived_at is null;
  if v_pid is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes)
      values (v_tid,'98d1b1fd-34af-556e-ba8a-ffe07efb5c51','accommodation','Residência estudantil — quarto individual, banheiro compartilhado, sem refeições','supplier','quotable','active','week',1,52,'{"seed": "planilha-2026-09", "slug": "bels-gozo-malta-residence-single-none", "category": null, "availability_status": "Requer confirmação", "link": "https://belsmalta.com/accommodation/gozo/bels-superior-residence/", "supplements": {"high_season_supplement": "30", "high_season_period": "28/jun a 29/ago", "low_season_discount": "30", "low_season_period": "3/jan a 28/fev e 1/nov a 31/dez", "private_bathroom_supplement": "70", "extra_night_fee": "70", "damage_deposit": "100", "other_supplement_fee": "10.5"}}'::jsonb) returning id into v_pid;
    insert into accommodation_detail (product_id, accommodation_type, room_type, bathroom_type, meal_plan) values (v_pid,'residence','private','shared','none');
    insert into product_content (product_id, locale, description_html, highlights, exclusions) values (v_pid,'pt-BR','<p>Quarto individual (privativo). Banheiro compartilhado (banheiro privativo disponível como upgrade, mediante taxa extra). Sem plano de refeições incluído — acomodação self-catering, com cozinha equipada. Inclui: Wi-Fi, ar-condicionado/aquecimento, máquina de lavar, roupa de cama, toalhas e transporte de chegada do aeroporto. Não inclui: refeições.</p><p>Suplementos e condições: Suplemento de alta temporada: EUR 30/semana (28/jun a 29/ago); Desconto de baixa temporada: EUR 30/semana (3/jan a 28/fev e 1/nov a 31/dez); Suplemento banheiro privativo: EUR 70/semana; Noite extra: EUR 70; Depósito caução (reembolsável): EUR 100; Outro suplemento: EUR 10.5.</p><p>Ajuste sazonal da acomodação, por semana: alta temporada 28/jun a 29/ago +€30; baixa temporada 3/jan a 28/fev e 1/nov a 31/dez -€30; média temporada 1/mar a 27/jun e 30/ago a 31/out sem ajuste. O ajuste não se aplica a reservas de 12+ semanas. Taxa obrigatória: Eco Tax (18+) €10,50 por semana, máximo €22,50 por estadia. Transfer de chegada com check-in €60 (obrigatório) e transfer de saída €60 (opcional); pessoa adicional no mesmo transfer €10. Alteração de reserva €30. Opcionais por semana: banheiro privativo €70 (mediante solicitação, em quarto individual); seguro €17. Noite extra €70 por noite. Depósito caução reembolsável de €100 em dinheiro, recolhido no primeiro dia de aula para quem fica em residência BELS e devolvido no último dia se não houver danos. Semanas calculadas em estadias de 7 noites (check-in sábado/domingo, entrada 15:00 e saída 10:00); noites extras para chegada antecipada ou saída tardia são cobradas à parte. Fonte: BELS Malta Price List 2026 (atualização fev/2026).</p>','["Residência moderna no centro de Victoria (Gozo), a poucos minutos a pé da estação de ônibus principal; cozinha totalmente equipada, ar-condicionado/aquecimento, máquina de lavar e Wi-Fi de alta velocidade; áreas comuns para convívio com outros estudantes; limpeza semanal com troca de roupa de cama e toalhas; suporte 24/7 da equipe da escola.", "Ideal para quem busca praticidade e vida em comunidade, orçamento médio"]'::jsonb,'["Menos indicado para quem exige banheiro privativo garantido sem custo extra"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'98d1b1fd-34af-556e-ba8a-ffe07efb5c51','Residência estudantil — quarto individual, banheiro compartilhado, sem refeições','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,320.0,0);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,8,290.0,1);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,12,260.0,2);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,24,230.0,3);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_pid);
  end if;

  select tenant_id into v_tid from campus where id='98d1b1fd-34af-556e-ba8a-ffe07efb5c51';
  select id into v_pid from product where campus_id='98d1b1fd-34af-556e-ba8a-ffe07efb5c51' and kind='accommodation' and attributes->>'slug'='bels-gozo-malta-residence-superior-plus-ensuite-shared-none' and coalesce(attributes->>'category','')='Superior plus' and archived_at is null;
  if v_pid is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes)
      values (v_tid,'98d1b1fd-34af-556e-ba8a-ffe07efb5c51','accommodation','Residência estudantil Superior plus — quarto compartilhado, banheiro privativo, sem refeições','supplier','quotable','active','week',1,52,'{"seed": "planilha-2026-09", "slug": "bels-gozo-malta-residence-superior-plus-ensuite-shared-none", "category": "Superior plus", "availability_status": "Requer confirmação", "link": "https://belsmalta.com/accommodation/gozo/", "supplements": {"high_season_supplement": "30", "high_season_period": "28/jun a 29/ago", "low_season_discount": "30", "low_season_period": "3/jan a 28/fev e 1/nov a 31/dez", "extra_night_fee": "70", "damage_deposit": "100", "other_supplement_fee": "10.5"}}'::jsonb) returning id into v_pid;
    insert into accommodation_detail (product_id, accommodation_type, room_type, bathroom_type, meal_plan) values (v_pid,'residence','shared_2','private','none');
    insert into product_content (product_id, locale, description_html, highlights, exclusions) values (v_pid,'pt-BR','<p>Quarto duplo (twin) compartilhado com outro estudante do mesmo gênero, na categoria Superior Plus com banheiro privativo (ensuite) incluído. Sem plano de refeições — self-catering, com cozinha equipada. Inclui: banheiro privativo, Wi-Fi de alta velocidade, ar-condicionado/aquecimento, máquina de lavar, roupa de cama, toalhas e limpeza semanal. Não inclui: refeições. Valor por pessoa/semana, com desconto progressivo a partir de 8 semanas.</p><p>Suplementos e condições: Suplemento de alta temporada: EUR 30/semana (28/jun a 29/ago); Desconto de baixa temporada: EUR 30/semana (3/jan a 28/fev e 1/nov a 31/dez); Noite extra: EUR 70; Depósito caução (reembolsável): EUR 100; Outro suplemento: EUR 10.5.</p><p>Ajuste sazonal da acomodação, por semana: alta temporada 28/jun a 29/ago +€30; baixa temporada 3/jan a 28/fev e 1/nov a 31/dez -€30; média temporada 1/mar a 27/jun e 30/ago a 31/out sem ajuste. O ajuste não se aplica a reservas de 12+ semanas. Taxa obrigatória: Eco Tax (18+) €10,50 por semana, máximo €22,50 por estadia. Transfer de chegada com check-in €60 (obrigatório) e transfer de saída €60 (opcional); pessoa adicional no mesmo transfer €10. Alteração de reserva €30. Opcionais por semana: seguro €17. Noite extra €70 por noite. Depósito caução reembolsável de €100 em dinheiro, recolhido no primeiro dia de aula para quem fica em residência BELS e devolvido no último dia se não houver danos. Semanas calculadas em estadias de 7 noites (check-in sábado/domingo, entrada 15:00 e saída 10:00); noites extras para chegada antecipada ou saída tardia são cobradas à parte. Fonte: BELS Malta Price List 2026 (atualização fev/2026).</p>','["Residência superior da BELS em Gozo, com quartos de padrão superior e banheiro privativo incluído; cozinha totalmente equipada, ar-condicionado/aquecimento, máquina de lavar e Wi-Fi de alta velocidade; áreas comuns para socializar; limpeza semanal com troca de roupa de cama e toalhas; suporte 24/7 da equipe da escola. Em Gozo, o quarto twin só é possível quando duas pessoas viajam juntas.", "Ideal para quem quer banheiro privativo em Gozo dividindo o quarto com um acompanhante"]'::jsonb,'["Menos indicado para quem viaja sozinho e quer quarto twin, que em Gozo só é liberado para duplas"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'98d1b1fd-34af-556e-ba8a-ffe07efb5c51','Residência estudantil Superior plus — quarto compartilhado, banheiro privativo, sem refeições','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,295.0,0);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,8,265.0,1);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,12,235.0,2);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,24,205.0,3);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_pid);
  end if;

  select tenant_id into v_tid from campus where id='98d1b1fd-34af-556e-ba8a-ffe07efb5c51';
  select id into v_pid from product where campus_id='98d1b1fd-34af-556e-ba8a-ffe07efb5c51' and kind='accommodation' and attributes->>'slug'='bels-gozo-malta-residence-superior-plus-ensuite-single-none' and coalesce(attributes->>'category','')='Superior plus' and archived_at is null;
  if v_pid is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes)
      values (v_tid,'98d1b1fd-34af-556e-ba8a-ffe07efb5c51','accommodation','Residência estudantil Superior plus — quarto individual, banheiro privativo, sem refeições','supplier','quotable','active','week',1,52,'{"seed": "planilha-2026-09", "slug": "bels-gozo-malta-residence-superior-plus-ensuite-single-none", "category": "Superior plus", "availability_status": "Requer confirmação", "link": "https://belsmalta.com/accommodation/gozo/", "supplements": {"high_season_supplement": "30", "high_season_period": "28/jun a 29/ago", "low_season_discount": "30", "low_season_period": "3/jan a 28/fev e 1/nov a 31/dez", "extra_night_fee": "70", "damage_deposit": "100", "other_supplement_fee": "10.5"}}'::jsonb) returning id into v_pid;
    insert into accommodation_detail (product_id, accommodation_type, room_type, bathroom_type, meal_plan) values (v_pid,'residence','private','private','none');
    insert into product_content (product_id, locale, description_html, highlights, exclusions) values (v_pid,'pt-BR','<p>Quarto individual (privativo) na categoria Superior Plus com banheiro privativo (ensuite) incluído. Sem plano de refeições — self-catering, com cozinha equipada. Inclui: banheiro privativo, Wi-Fi de alta velocidade, ar-condicionado/aquecimento, máquina de lavar, roupa de cama, toalhas e limpeza semanal. Não inclui: refeições. Valor por pessoa/semana, com desconto progressivo a partir de 8 semanas.</p><p>Suplementos e condições: Suplemento de alta temporada: EUR 30/semana (28/jun a 29/ago); Desconto de baixa temporada: EUR 30/semana (3/jan a 28/fev e 1/nov a 31/dez); Noite extra: EUR 70; Depósito caução (reembolsável): EUR 100; Outro suplemento: EUR 10.5.</p><p>Ajuste sazonal da acomodação, por semana: alta temporada 28/jun a 29/ago +€30; baixa temporada 3/jan a 28/fev e 1/nov a 31/dez -€30; média temporada 1/mar a 27/jun e 30/ago a 31/out sem ajuste. O ajuste não se aplica a reservas de 12+ semanas. Taxa obrigatória: Eco Tax (18+) €10,50 por semana, máximo €22,50 por estadia. Transfer de chegada com check-in €60 (obrigatório) e transfer de saída €60 (opcional); pessoa adicional no mesmo transfer €10. Alteração de reserva €30. Opcionais por semana: seguro €17. Noite extra €70 por noite. Depósito caução reembolsável de €100 em dinheiro, recolhido no primeiro dia de aula para quem fica em residência BELS e devolvido no último dia se não houver danos. Semanas calculadas em estadias de 7 noites (check-in sábado/domingo, entrada 15:00 e saída 10:00); noites extras para chegada antecipada ou saída tardia são cobradas à parte. Fonte: BELS Malta Price List 2026 (atualização fev/2026).</p>','["Residência superior da BELS em Gozo, com quartos de padrão superior e banheiro privativo incluído; cozinha totalmente equipada, ar-condicionado/aquecimento, máquina de lavar e Wi-Fi de alta velocidade; áreas comuns para socializar; limpeza semanal com troca de roupa de cama e toalhas; suporte 24/7 da equipe da escola. Em Gozo, o quarto twin só é possível quando duas pessoas viajam juntas.", "Ideal para quem quer privacidade total em Gozo: quarto individual e banheiro privativo"]'::jsonb,'["Menos indicado para quem tem orçamento apertado ou quer refeições incluídas"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'98d1b1fd-34af-556e-ba8a-ffe07efb5c51','Residência estudantil Superior plus — quarto individual, banheiro privativo, sem refeições','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,425.0,0);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,8,395.0,1);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,12,365.0,2);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,24,335.0,3);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_pid);
  end if;
end $$;