do $$ declare v_pid uuid; v_tid uuid; v_tpl uuid; v_fee uuid; v_new uuid; begin
  select tenant_id into v_tid from campus where id='98d1b1fd-34af-556e-ba8a-ffe07efb5c51';
  select id into v_fee from fee where campus_id='98d1b1fd-34af-556e-ba8a-ffe07efb5c51' and fee_type='material' and archived_at is null and name='Material didático' limit 1;

  if not exists (select 1 from price_template_product l join price_template t on t.id=l.price_template_id where l.product_id='a2e53a4a-cb6a-51da-9d3a-58dcf0900bbf' and t.status='active') then
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'98d1b1fd-34af-556e-ba8a-ffe07efb5c51','English for Engireeing — 5 aulas individuais/semana','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,200,0);
    insert into price_template_product (price_template_id, product_id) values (v_tpl,'a2e53a4a-cb6a-51da-9d3a-58dcf0900bbf');
    update product set visibility='quotable', min_duration=1, max_duration=52, updated_at=now() where id='a2e53a4a-cb6a-51da-9d3a-58dcf0900bbf';
  end if;
  insert into fee_product (fee_id, product_id) values (v_fee,'a2e53a4a-cb6a-51da-9d3a-58dcf0900bbf') on conflict do nothing;

  select id into v_new from product where campus_id='98d1b1fd-34af-556e-ba8a-ffe07efb5c51' and kind='program' and attributes->>'slug'='bels-gozo-malta-general-english-20-english-for-engireeing' and archived_at is null;
  if v_new is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes) values (v_tid,'98d1b1fd-34af-556e-ba8a-ffe07efb5c51','program','General English 20 + English for Engireeing','supplier','quotable','active','week',1,11,'{"seed": "planilha-2026-09", "slug": "bels-gozo-malta-general-english-20-english-for-engireeing", "course_type": "english-for-specific-purposes", "base_product_slug": "bels-gozo-malta-english-for-engireeing"}'::jsonb) returning id into v_new;
    insert into program_detail (product_id, education_type, language, delivery_method, lessons_per_week, hours_per_week, timetable) values (v_new,'english-for-specific-purposes','English','in_person',25,18.75,'{"start_frequency": "Semanal - início em qualquer segunda-feira (BELS FAQ); estadia mínima de 1 semana.", "class_schedule": "Segunda a sexta: General English Standard 09:15-10:45 e 11:15-12:45 (20 lições de 45 min) + 5 lições individuais de ESP em horário flexível (segunda a sábado). Cursos de 1 a 7 semanas tem aulas garantidas pela manhã; a partir de 8 semanas pode haver double-banking.", "non_refundable_fees": "Taxa de inscrição/administrativa de EUR 55 não reembolsável em qualquer cancelamento (até 22 dias antes do início: reembolso total menos EUR 55). 21 dias antes: retenção de 25% da fatura; 20 a 8 dias: 50%; 7 dias ou menos, ou no-show: sem reembolso. Recusa de visto: reembolso do valor bruto menos taxa de registro, taxa de processamento de visto e encargos bancários. Taxas administrativas de assistência a visto não sao devolvidas se o visto for recusado. Sem reembolso em caso de expulsão. Adiamentos: o 1o e gratuito, os seguintes custam EUR 30. Depósito de danos e reembolsável.", "entry_level": "A2/B1", "lesson_minutes": 45, "source": "planilha-2026-09"}'::jsonb);
    insert into product_content (product_id, locale, description_html, highlights) values (v_new,'pt-BR','<p>Combinação de General English (20 aulas em grupo por semana) com English for Engireeing (5 aulas individuais por semana), totalizando 25 aulas semanais.</p><p>Segunda a sexta: General English Standard 09:15-10:45 e 11:15-12:45 (20 lições de 45 min) + 5 lições individuais de ESP em horário flexível (segunda a sábado). Cursos de 1 a 7 semanas tem aulas garantidas pela manhã; a partir de 8 semanas pode haver double-banking.</p>','["20 aulas de General English em grupo (09:15–12:45)", "5 aulas individuais da área profissional", "Análise de necessidades no primeiro dia", "Duração de 1 a 11 semanas"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'98d1b1fd-34af-556e-ba8a-ffe07efb5c51','General English 20 + English for Engireeing','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,450,0);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,8,425,1);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_new);
    insert into fee_product (fee_id, product_id) values (v_fee, v_new);
    insert into fee_product (fee_id, product_id) select f.id, v_new from fee f where f.campus_id='98d1b1fd-34af-556e-ba8a-ffe07efb5c51' and f.fee_type='registration' and f.archived_at is null limit 1;
  end if;

  if not exists (select 1 from price_template_product l join price_template t on t.id=l.price_template_id where l.product_id='2070ea1f-c08c-57ce-b8d3-a28e6e72fe53' and t.status='active') then
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'98d1b1fd-34af-556e-ba8a-ffe07efb5c51','English for Food and Beverage — 5 aulas individuais/semana','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,200,0);
    insert into price_template_product (price_template_id, product_id) values (v_tpl,'2070ea1f-c08c-57ce-b8d3-a28e6e72fe53');
    update product set visibility='quotable', min_duration=1, max_duration=52, updated_at=now() where id='2070ea1f-c08c-57ce-b8d3-a28e6e72fe53';
  end if;
  insert into fee_product (fee_id, product_id) values (v_fee,'2070ea1f-c08c-57ce-b8d3-a28e6e72fe53') on conflict do nothing;

  select id into v_new from product where campus_id='98d1b1fd-34af-556e-ba8a-ffe07efb5c51' and kind='program' and attributes->>'slug'='bels-gozo-malta-general-english-20-english-for-food-and-beverage' and archived_at is null;
  if v_new is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes) values (v_tid,'98d1b1fd-34af-556e-ba8a-ffe07efb5c51','program','General English 20 + English for Food and Beverage','supplier','quotable','active','week',1,11,'{"seed": "planilha-2026-09", "slug": "bels-gozo-malta-general-english-20-english-for-food-and-beverage", "course_type": "english-for-specific-purposes", "base_product_slug": "bels-gozo-malta-english-for-food-and-beverage"}'::jsonb) returning id into v_new;
    insert into program_detail (product_id, education_type, language, delivery_method, lessons_per_week, hours_per_week, timetable) values (v_new,'english-for-specific-purposes','English','in_person',25,18.75,'{"start_frequency": "Semanal - início em qualquer segunda-feira (BELS FAQ); estadia mínima de 1 semana.", "class_schedule": "Segunda a sexta: General English Standard 09:15-10:45 e 11:15-12:45 (20 lições de 45 min) + 5 lições individuais de ESP em horário flexível (segunda a sábado). Cursos de 1 a 7 semanas tem aulas garantidas pela manhã; a partir de 8 semanas pode haver double-banking.", "non_refundable_fees": "Taxa de inscrição/administrativa de EUR 55 não reembolsável em qualquer cancelamento (até 22 dias antes do início: reembolso total menos EUR 55). 21 dias antes: retenção de 25% da fatura; 20 a 8 dias: 50%; 7 dias ou menos, ou no-show: sem reembolso. Recusa de visto: reembolso do valor bruto menos taxa de registro, taxa de processamento de visto e encargos bancários. Taxas administrativas de assistência a visto não sao devolvidas se o visto for recusado. Sem reembolso em caso de expulsão. Adiamentos: o 1o e gratuito, os seguintes custam EUR 30. Depósito de danos e reembolsável.", "entry_level": "A2/B1", "lesson_minutes": 45, "source": "planilha-2026-09"}'::jsonb);
    insert into product_content (product_id, locale, description_html, highlights) values (v_new,'pt-BR','<p>Combinação de General English (20 aulas em grupo por semana) com English for Food and Beverage (5 aulas individuais por semana), totalizando 25 aulas semanais.</p><p>Segunda a sexta: General English Standard 09:15-10:45 e 11:15-12:45 (20 lições de 45 min) + 5 lições individuais de ESP em horário flexível (segunda a sábado). Cursos de 1 a 7 semanas tem aulas garantidas pela manhã; a partir de 8 semanas pode haver double-banking.</p>','["20 aulas de General English em grupo (09:15–12:45)", "5 aulas individuais da área profissional", "Análise de necessidades no primeiro dia", "Duração de 1 a 11 semanas"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'98d1b1fd-34af-556e-ba8a-ffe07efb5c51','General English 20 + English for Food and Beverage','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,450,0);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,8,425,1);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_new);
    insert into fee_product (fee_id, product_id) values (v_fee, v_new);
    insert into fee_product (fee_id, product_id) select f.id, v_new from fee f where f.campus_id='98d1b1fd-34af-556e-ba8a-ffe07efb5c51' and f.fee_type='registration' and f.archived_at is null limit 1;
  end if;

  if not exists (select 1 from price_template_product l join price_template t on t.id=l.price_template_id where l.product_id='816b7fa5-b94c-5e29-88d9-7ad3b73d82bd' and t.status='active') then
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'98d1b1fd-34af-556e-ba8a-ffe07efb5c51','English for Human Resources — 5 aulas individuais/semana','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,200,0);
    insert into price_template_product (price_template_id, product_id) values (v_tpl,'816b7fa5-b94c-5e29-88d9-7ad3b73d82bd');
    update product set visibility='quotable', min_duration=1, max_duration=52, updated_at=now() where id='816b7fa5-b94c-5e29-88d9-7ad3b73d82bd';
  end if;
  insert into fee_product (fee_id, product_id) values (v_fee,'816b7fa5-b94c-5e29-88d9-7ad3b73d82bd') on conflict do nothing;

  select id into v_new from product where campus_id='98d1b1fd-34af-556e-ba8a-ffe07efb5c51' and kind='program' and attributes->>'slug'='bels-gozo-malta-general-english-20-english-for-human-resources' and archived_at is null;
  if v_new is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes) values (v_tid,'98d1b1fd-34af-556e-ba8a-ffe07efb5c51','program','General English 20 + English for Human Resources','supplier','quotable','active','week',1,11,'{"seed": "planilha-2026-09", "slug": "bels-gozo-malta-general-english-20-english-for-human-resources", "course_type": "english-for-specific-purposes", "base_product_slug": "bels-gozo-malta-english-for-human-resources"}'::jsonb) returning id into v_new;
    insert into program_detail (product_id, education_type, language, delivery_method, lessons_per_week, hours_per_week, timetable) values (v_new,'english-for-specific-purposes','English','in_person',25,18.75,'{"start_frequency": "Semanal - início em qualquer segunda-feira (BELS FAQ); estadia mínima de 1 semana.", "class_schedule": "Segunda a sexta: General English Standard 09:15-10:45 e 11:15-12:45 (20 lições de 45 min) + 5 lições individuais de ESP em horário flexível (segunda a sábado). Cursos de 1 a 7 semanas tem aulas garantidas pela manhã; a partir de 8 semanas pode haver double-banking.", "non_refundable_fees": "Taxa de inscrição/administrativa de EUR 55 não reembolsável em qualquer cancelamento (até 22 dias antes do início: reembolso total menos EUR 55). 21 dias antes: retenção de 25% da fatura; 20 a 8 dias: 50%; 7 dias ou menos, ou no-show: sem reembolso. Recusa de visto: reembolso do valor bruto menos taxa de registro, taxa de processamento de visto e encargos bancários. Taxas administrativas de assistência a visto não sao devolvidas se o visto for recusado. Sem reembolso em caso de expulsão. Adiamentos: o 1o e gratuito, os seguintes custam EUR 30. Depósito de danos e reembolsável.", "entry_level": "A1/B2", "lesson_minutes": 45, "source": "planilha-2026-09"}'::jsonb);
    insert into product_content (product_id, locale, description_html, highlights) values (v_new,'pt-BR','<p>Combinação de General English (20 aulas em grupo por semana) com English for Human Resources (5 aulas individuais por semana), totalizando 25 aulas semanais.</p><p>Segunda a sexta: General English Standard 09:15-10:45 e 11:15-12:45 (20 lições de 45 min) + 5 lições individuais de ESP em horário flexível (segunda a sábado). Cursos de 1 a 7 semanas tem aulas garantidas pela manhã; a partir de 8 semanas pode haver double-banking.</p>','["20 aulas de General English em grupo (09:15–12:45)", "5 aulas individuais da área profissional", "Análise de necessidades no primeiro dia", "Duração de 1 a 11 semanas"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'98d1b1fd-34af-556e-ba8a-ffe07efb5c51','General English 20 + English for Human Resources','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,450,0);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,8,425,1);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_new);
    insert into fee_product (fee_id, product_id) values (v_fee, v_new);
    insert into fee_product (fee_id, product_id) select f.id, v_new from fee f where f.campus_id='98d1b1fd-34af-556e-ba8a-ffe07efb5c51' and f.fee_type='registration' and f.archived_at is null limit 1;
  end if;

  if not exists (select 1 from price_template_product l join price_template t on t.id=l.price_template_id where l.product_id='c5a10803-e7f4-5686-93c7-63fe365d26b1' and t.status='active') then
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'98d1b1fd-34af-556e-ba8a-ffe07efb5c51','English for Information Technology — 5 aulas individuais/semana','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,200,0);
    insert into price_template_product (price_template_id, product_id) values (v_tpl,'c5a10803-e7f4-5686-93c7-63fe365d26b1');
    update product set visibility='quotable', min_duration=1, max_duration=52, updated_at=now() where id='c5a10803-e7f4-5686-93c7-63fe365d26b1';
  end if;
  insert into fee_product (fee_id, product_id) values (v_fee,'c5a10803-e7f4-5686-93c7-63fe365d26b1') on conflict do nothing;

  select id into v_new from product where campus_id='98d1b1fd-34af-556e-ba8a-ffe07efb5c51' and kind='program' and attributes->>'slug'='bels-gozo-malta-general-english-20-english-for-information-technology' and archived_at is null;
  if v_new is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes) values (v_tid,'98d1b1fd-34af-556e-ba8a-ffe07efb5c51','program','General English 20 + English for Information Technology','supplier','quotable','active','week',1,11,'{"seed": "planilha-2026-09", "slug": "bels-gozo-malta-general-english-20-english-for-information-technology", "course_type": "english-for-specific-purposes", "base_product_slug": "bels-gozo-malta-english-for-information-technology"}'::jsonb) returning id into v_new;
    insert into program_detail (product_id, education_type, language, delivery_method, lessons_per_week, hours_per_week, timetable) values (v_new,'english-for-specific-purposes','English','in_person',25,18.75,'{"start_frequency": "Semanal - início em qualquer segunda-feira (BELS FAQ); estadia mínima de 1 semana.", "class_schedule": "Segunda a sexta: General English Standard 09:15-10:45 e 11:15-12:45 (20 lições de 45 min) + 5 lições individuais de ESP em horário flexível (segunda a sábado). Cursos de 1 a 7 semanas tem aulas garantidas pela manhã; a partir de 8 semanas pode haver double-banking.", "non_refundable_fees": "Taxa de inscrição/administrativa de EUR 55 não reembolsável em qualquer cancelamento (até 22 dias antes do início: reembolso total menos EUR 55). 21 dias antes: retenção de 25% da fatura; 20 a 8 dias: 50%; 7 dias ou menos, ou no-show: sem reembolso. Recusa de visto: reembolso do valor bruto menos taxa de registro, taxa de processamento de visto e encargos bancários. Taxas administrativas de assistência a visto não sao devolvidas se o visto for recusado. Sem reembolso em caso de expulsão. Adiamentos: o 1o e gratuito, os seguintes custam EUR 30. Depósito de danos e reembolsável.", "entry_level": "A2", "lesson_minutes": 45, "source": "planilha-2026-09"}'::jsonb);
    insert into product_content (product_id, locale, description_html, highlights) values (v_new,'pt-BR','<p>Combinação de General English (20 aulas em grupo por semana) com English for Information Technology (5 aulas individuais por semana), totalizando 25 aulas semanais.</p><p>Segunda a sexta: General English Standard 09:15-10:45 e 11:15-12:45 (20 lições de 45 min) + 5 lições individuais de ESP em horário flexível (segunda a sábado). Cursos de 1 a 7 semanas tem aulas garantidas pela manhã; a partir de 8 semanas pode haver double-banking.</p>','["20 aulas de General English em grupo (09:15–12:45)", "5 aulas individuais da área profissional", "Análise de necessidades no primeiro dia", "Duração de 1 a 11 semanas"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'98d1b1fd-34af-556e-ba8a-ffe07efb5c51','General English 20 + English for Information Technology','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,450,0);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,8,425,1);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_new);
    insert into fee_product (fee_id, product_id) values (v_fee, v_new);
    insert into fee_product (fee_id, product_id) select f.id, v_new from fee f where f.campus_id='98d1b1fd-34af-556e-ba8a-ffe07efb5c51' and f.fee_type='registration' and f.archived_at is null limit 1;
  end if;

  if not exists (select 1 from price_template_product l join price_template t on t.id=l.price_template_id where l.product_id='bb9fe20b-11d1-5624-a8b5-630e82805d8c' and t.status='active') then
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'98d1b1fd-34af-556e-ba8a-ffe07efb5c51','English for Insurance Companies — 5 aulas individuais/semana','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,200,0);
    insert into price_template_product (price_template_id, product_id) values (v_tpl,'bb9fe20b-11d1-5624-a8b5-630e82805d8c');
    update product set visibility='quotable', min_duration=1, max_duration=52, updated_at=now() where id='bb9fe20b-11d1-5624-a8b5-630e82805d8c';
  end if;
  insert into fee_product (fee_id, product_id) values (v_fee,'bb9fe20b-11d1-5624-a8b5-630e82805d8c') on conflict do nothing;

  select id into v_new from product where campus_id='98d1b1fd-34af-556e-ba8a-ffe07efb5c51' and kind='program' and attributes->>'slug'='bels-gozo-malta-general-english-20-english-for-insurance-companies' and archived_at is null;
  if v_new is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes) values (v_tid,'98d1b1fd-34af-556e-ba8a-ffe07efb5c51','program','General English 20 + English for Insurance Companies','supplier','quotable','active','week',1,11,'{"seed": "planilha-2026-09", "slug": "bels-gozo-malta-general-english-20-english-for-insurance-companies", "course_type": "english-for-specific-purposes", "base_product_slug": "bels-gozo-malta-english-for-insurance-companies"}'::jsonb) returning id into v_new;
    insert into program_detail (product_id, education_type, language, delivery_method, lessons_per_week, hours_per_week, timetable) values (v_new,'english-for-specific-purposes','English','in_person',25,18.75,'{"start_frequency": "Semanal - início em qualquer segunda-feira (BELS FAQ); estadia mínima de 1 semana.", "class_schedule": "Segunda a sexta: General English Standard 09:15-10:45 e 11:15-12:45 (20 lições de 45 min) + 5 lições individuais de ESP em horário flexível (segunda a sábado). Cursos de 1 a 7 semanas tem aulas garantidas pela manhã; a partir de 8 semanas pode haver double-banking.", "non_refundable_fees": "Taxa de inscrição/administrativa de EUR 55 não reembolsável em qualquer cancelamento (até 22 dias antes do início: reembolso total menos EUR 55). 21 dias antes: retenção de 25% da fatura; 20 a 8 dias: 50%; 7 dias ou menos, ou no-show: sem reembolso. Recusa de visto: reembolso do valor bruto menos taxa de registro, taxa de processamento de visto e encargos bancários. Taxas administrativas de assistência a visto não sao devolvidas se o visto for recusado. Sem reembolso em caso de expulsão. Adiamentos: o 1o e gratuito, os seguintes custam EUR 30. Depósito de danos e reembolsável.", "entry_level": "A2/B1", "lesson_minutes": 45, "source": "planilha-2026-09"}'::jsonb);
    insert into product_content (product_id, locale, description_html, highlights) values (v_new,'pt-BR','<p>Combinação de General English (20 aulas em grupo por semana) com English for Insurance Companies (5 aulas individuais por semana), totalizando 25 aulas semanais.</p><p>Segunda a sexta: General English Standard 09:15-10:45 e 11:15-12:45 (20 lições de 45 min) + 5 lições individuais de ESP em horário flexível (segunda a sábado). Cursos de 1 a 7 semanas tem aulas garantidas pela manhã; a partir de 8 semanas pode haver double-banking.</p>','["20 aulas de General English em grupo (09:15–12:45)", "5 aulas individuais da área profissional", "Análise de necessidades no primeiro dia", "Duração de 1 a 11 semanas"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'98d1b1fd-34af-556e-ba8a-ffe07efb5c51','General English 20 + English for Insurance Companies','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,450,0);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,8,425,1);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_new);
    insert into fee_product (fee_id, product_id) values (v_fee, v_new);
    insert into fee_product (fee_id, product_id) select f.id, v_new from fee f where f.campus_id='98d1b1fd-34af-556e-ba8a-ffe07efb5c51' and f.fee_type='registration' and f.archived_at is null limit 1;
  end if;

  if not exists (select 1 from price_template_product l join price_template t on t.id=l.price_template_id where l.product_id='65076c78-00b9-53b1-ac5d-dcbaba76e008' and t.status='active') then
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'98d1b1fd-34af-556e-ba8a-ffe07efb5c51','English for Management — 5 aulas individuais/semana','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,200,0);
    insert into price_template_product (price_template_id, product_id) values (v_tpl,'65076c78-00b9-53b1-ac5d-dcbaba76e008');
    update product set visibility='quotable', min_duration=1, max_duration=52, updated_at=now() where id='65076c78-00b9-53b1-ac5d-dcbaba76e008';
  end if;
  insert into fee_product (fee_id, product_id) values (v_fee,'65076c78-00b9-53b1-ac5d-dcbaba76e008') on conflict do nothing;

  select id into v_new from product where campus_id='98d1b1fd-34af-556e-ba8a-ffe07efb5c51' and kind='program' and attributes->>'slug'='bels-gozo-malta-general-english-20-english-for-management' and archived_at is null;
  if v_new is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes) values (v_tid,'98d1b1fd-34af-556e-ba8a-ffe07efb5c51','program','General English 20 + English for Management','supplier','quotable','active','week',1,11,'{"seed": "planilha-2026-09", "slug": "bels-gozo-malta-general-english-20-english-for-management", "course_type": "english-for-specific-purposes", "base_product_slug": "bels-gozo-malta-english-for-management"}'::jsonb) returning id into v_new;
    insert into program_detail (product_id, education_type, language, delivery_method, lessons_per_week, hours_per_week, timetable) values (v_new,'english-for-specific-purposes','English','in_person',25,18.75,'{"start_frequency": "Semanal - início em qualquer segunda-feira (BELS FAQ); estadia mínima de 1 semana.", "class_schedule": "Segunda a sexta: General English Standard 09:15-10:45 e 11:15-12:45 (20 lições de 45 min) + 5 lições individuais de ESP em horário flexível (segunda a sábado). Cursos de 1 a 7 semanas tem aulas garantidas pela manhã; a partir de 8 semanas pode haver double-banking.", "non_refundable_fees": "Taxa de inscrição/administrativa de EUR 55 não reembolsável em qualquer cancelamento (até 22 dias antes do início: reembolso total menos EUR 55). 21 dias antes: retenção de 25% da fatura; 20 a 8 dias: 50%; 7 dias ou menos, ou no-show: sem reembolso. Recusa de visto: reembolso do valor bruto menos taxa de registro, taxa de processamento de visto e encargos bancários. Taxas administrativas de assistência a visto não sao devolvidas se o visto for recusado. Sem reembolso em caso de expulsão. Adiamentos: o 1o e gratuito, os seguintes custam EUR 30. Depósito de danos e reembolsável.", "entry_level": "A2/B1", "lesson_minutes": 45, "source": "planilha-2026-09"}'::jsonb);
    insert into product_content (product_id, locale, description_html, highlights) values (v_new,'pt-BR','<p>Combinação de General English (20 aulas em grupo por semana) com English for Management (5 aulas individuais por semana), totalizando 25 aulas semanais.</p><p>Segunda a sexta: General English Standard 09:15-10:45 e 11:15-12:45 (20 lições de 45 min) + 5 lições individuais de ESP em horário flexível (segunda a sábado). Cursos de 1 a 7 semanas tem aulas garantidas pela manhã; a partir de 8 semanas pode haver double-banking.</p>','["20 aulas de General English em grupo (09:15–12:45)", "5 aulas individuais da área profissional", "Análise de necessidades no primeiro dia", "Duração de 1 a 11 semanas"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'98d1b1fd-34af-556e-ba8a-ffe07efb5c51','General English 20 + English for Management','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,450,0);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,8,425,1);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_new);
    insert into fee_product (fee_id, product_id) values (v_fee, v_new);
    insert into fee_product (fee_id, product_id) select f.id, v_new from fee f where f.campus_id='98d1b1fd-34af-556e-ba8a-ffe07efb5c51' and f.fee_type='registration' and f.archived_at is null limit 1;
  end if;
end $$;