do $$ declare v_pid uuid; v_tid uuid; v_tpl uuid; v_fee uuid; v_new uuid; begin
  select tenant_id into v_tid from campus where id='cea43266-51db-5e14-8c4b-b4f24611d620';
  select id into v_fee from fee where campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and fee_type='material' and archived_at is null and name='Material didático' limit 1;
  if v_fee is null then insert into fee (tenant_id, campus_id, name, fee_type, charge_basis, amount, currency, is_mandatory, is_refundable, applies_to_kinds) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','Material didático','material','per_unit',30,'EUR',true,false,array['program']) returning id into v_fee; end if;
  update price_tier set unit_price=17 where price_template_id in (select l.price_template_id from price_template_product l join product p on p.id=l.product_id where p.campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and p.kind='insurance' and p.archived_at is null);

  if not exists (select 1 from price_template_product l join price_template t on t.id=l.price_template_id where l.product_id='d27386ec-f09a-556a-8a79-b8046e722c7e' and t.status='active') then
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','English for Accounting and Finance — 5 aulas individuais/semana','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,200,0);
    insert into price_template_product (price_template_id, product_id) values (v_tpl,'d27386ec-f09a-556a-8a79-b8046e722c7e');
    update product set visibility='quotable', min_duration=1, max_duration=52, updated_at=now() where id='d27386ec-f09a-556a-8a79-b8046e722c7e';
  end if;
  insert into fee_product (fee_id, product_id) values (v_fee,'d27386ec-f09a-556a-8a79-b8046e722c7e') on conflict do nothing;

  select id into v_new from product where campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and kind='program' and attributes->>'slug'='bels-st-pauls-bay-malta-general-english-20-english-for-accounting-and-finance' and archived_at is null;
  if v_new is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','program','General English 20 + English for Accounting and Finance','supplier','quotable','active','week',1,11,'{"seed": "planilha-2026-09", "slug": "bels-st-pauls-bay-malta-general-english-20-english-for-accounting-and-finance", "course_type": "english-for-specific-purposes", "base_product_slug": "bels-gozo-malta-english-for-accounting-and-finance"}'::jsonb) returning id into v_new;
    insert into program_detail (product_id, education_type, language, delivery_method, lessons_per_week, hours_per_week, timetable) values (v_new,'english-for-specific-purposes','English','in_person',25,18.75,'{"start_frequency": "Semanal - início em qualquer segunda-feira (BELS FAQ); estadia mínima de 1 semana.", "class_schedule": "Segunda a sexta: General English Standard 09:15-10:45 e 11:15-12:45 (20 lições de 45 min) + 5 lições individuais de ESP em horário flexível (segunda a sábado). Cursos de 1 a 7 semanas tem aulas garantidas pela manhã; a partir de 8 semanas pode haver double-banking.", "non_refundable_fees": "Taxa de inscrição/administrativa de EUR 55 não reembolsável em qualquer cancelamento (até 22 dias antes do início: reembolso total menos EUR 55). 21 dias antes: retenção de 25% da fatura; 20 a 8 dias: 50%; 7 dias ou menos, ou no-show: sem reembolso. Recusa de visto: reembolso do valor bruto menos taxa de registro, taxa de processamento de visto e encargos bancários. Taxas administrativas de assistência a visto não sao devolvidas se o visto for recusado. Sem reembolso em caso de expulsão. Adiamentos: o 1o e gratuito, os seguintes custam EUR 30. Depósito de danos e reembolsável.", "entry_level": "A2/B1", "lesson_minutes": 45, "source": "planilha-2026-09"}'::jsonb);
    insert into product_content (product_id, locale, description_html, highlights) values (v_new,'pt-BR','<p>Combinação de General English (20 aulas em grupo por semana) com English for Accounting and Finance (5 aulas individuais por semana), totalizando 25 aulas semanais.</p><p>Segunda a sexta: General English Standard 09:15-10:45 e 11:15-12:45 (20 lições de 45 min) + 5 lições individuais de ESP em horário flexível (segunda a sábado). Cursos de 1 a 7 semanas tem aulas garantidas pela manhã; a partir de 8 semanas pode haver double-banking.</p>','["20 aulas de General English em grupo (09:15–12:45)", "5 aulas individuais da área profissional", "Análise de necessidades no primeiro dia", "Duração de 1 a 11 semanas"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','General English 20 + English for Accounting and Finance','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,450,0);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,8,425,1);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_new);
    insert into fee_product (fee_id, product_id) values (v_fee, v_new);
    insert into fee_product (fee_id, product_id) select f.id, v_new from fee f where f.campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and f.fee_type='registration' and f.archived_at is null limit 1;
  end if;

  if not exists (select 1 from price_template_product l join price_template t on t.id=l.price_template_id where l.product_id='47d6d101-375d-55e8-8671-845e93ab210f' and t.status='active') then
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','English for Administration — 5 aulas individuais/semana','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,200,0);
    insert into price_template_product (price_template_id, product_id) values (v_tpl,'47d6d101-375d-55e8-8671-845e93ab210f');
    update product set visibility='quotable', min_duration=1, max_duration=52, updated_at=now() where id='47d6d101-375d-55e8-8671-845e93ab210f';
  end if;
  insert into fee_product (fee_id, product_id) values (v_fee,'47d6d101-375d-55e8-8671-845e93ab210f') on conflict do nothing;

  select id into v_new from product where campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and kind='program' and attributes->>'slug'='bels-st-pauls-bay-malta-general-english-20-english-for-administration' and archived_at is null;
  if v_new is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','program','General English 20 + English for Administration','supplier','quotable','active','week',1,11,'{"seed": "planilha-2026-09", "slug": "bels-st-pauls-bay-malta-general-english-20-english-for-administration", "course_type": "english-for-specific-purposes", "base_product_slug": "bels-gozo-malta-english-for-administration"}'::jsonb) returning id into v_new;
    insert into program_detail (product_id, education_type, language, delivery_method, lessons_per_week, hours_per_week, timetable) values (v_new,'english-for-specific-purposes','English','in_person',25,18.75,'{"start_frequency": "Semanal - início em qualquer segunda-feira (BELS FAQ); estadia mínima de 1 semana.", "class_schedule": "Segunda a sexta: General English Standard 09:15-10:45 e 11:15-12:45 (20 lições de 45 min) + 5 lições individuais de ESP em horário flexível (segunda a sábado). Cursos de 1 a 7 semanas tem aulas garantidas pela manhã; a partir de 8 semanas pode haver double-banking.", "non_refundable_fees": "Taxa de inscrição/administrativa de EUR 55 não reembolsável em qualquer cancelamento (até 22 dias antes do início: reembolso total menos EUR 55). 21 dias antes: retenção de 25% da fatura; 20 a 8 dias: 50%; 7 dias ou menos, ou no-show: sem reembolso. Recusa de visto: reembolso do valor bruto menos taxa de registro, taxa de processamento de visto e encargos bancários. Taxas administrativas de assistência a visto não sao devolvidas se o visto for recusado. Sem reembolso em caso de expulsão. Adiamentos: o 1o e gratuito, os seguintes custam EUR 30. Depósito de danos e reembolsável.", "entry_level": "A2/B1", "lesson_minutes": 45, "source": "planilha-2026-09"}'::jsonb);
    insert into product_content (product_id, locale, description_html, highlights) values (v_new,'pt-BR','<p>Combinação de General English (20 aulas em grupo por semana) com English for Administration (5 aulas individuais por semana), totalizando 25 aulas semanais.</p><p>Segunda a sexta: General English Standard 09:15-10:45 e 11:15-12:45 (20 lições de 45 min) + 5 lições individuais de ESP em horário flexível (segunda a sábado). Cursos de 1 a 7 semanas tem aulas garantidas pela manhã; a partir de 8 semanas pode haver double-banking.</p>','["20 aulas de General English em grupo (09:15–12:45)", "5 aulas individuais da área profissional", "Análise de necessidades no primeiro dia", "Duração de 1 a 11 semanas"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','General English 20 + English for Administration','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,450,0);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,8,425,1);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_new);
    insert into fee_product (fee_id, product_id) values (v_fee, v_new);
    insert into fee_product (fee_id, product_id) select f.id, v_new from fee f where f.campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and f.fee_type='registration' and f.archived_at is null limit 1;
  end if;

  if not exists (select 1 from price_template_product l join price_template t on t.id=l.price_template_id where l.product_id='381989b5-328f-5aae-9c37-b713122218cb' and t.status='active') then
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','English for Aviation — 5 aulas individuais/semana','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,200,0);
    insert into price_template_product (price_template_id, product_id) values (v_tpl,'381989b5-328f-5aae-9c37-b713122218cb');
    update product set visibility='quotable', min_duration=1, max_duration=52, updated_at=now() where id='381989b5-328f-5aae-9c37-b713122218cb';
  end if;
  insert into fee_product (fee_id, product_id) values (v_fee,'381989b5-328f-5aae-9c37-b713122218cb') on conflict do nothing;

  select id into v_new from product where campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and kind='program' and attributes->>'slug'='bels-st-pauls-bay-malta-general-english-20-english-for-aviation' and archived_at is null;
  if v_new is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','program','General English 20 + English for Aviation','supplier','quotable','active','week',1,11,'{"seed": "planilha-2026-09", "slug": "bels-st-pauls-bay-malta-general-english-20-english-for-aviation", "course_type": "english-for-specific-purposes", "base_product_slug": "bels-gozo-malta-english-for-aviation"}'::jsonb) returning id into v_new;
    insert into program_detail (product_id, education_type, language, delivery_method, lessons_per_week, hours_per_week, timetable) values (v_new,'english-for-specific-purposes','English','in_person',25,18.75,'{"start_frequency": "Semanal - início em qualquer segunda-feira (BELS FAQ); estadia mínima de 1 semana.", "class_schedule": "Segunda a sexta: General English Standard 09:15-10:45 e 11:15-12:45 (20 lições de 45 min) + 5 lições individuais de ESP em horário flexível (segunda a sábado). Cursos de 1 a 7 semanas tem aulas garantidas pela manhã; a partir de 8 semanas pode haver double-banking.", "non_refundable_fees": "Taxa de inscrição/administrativa de EUR 55 não reembolsável em qualquer cancelamento (até 22 dias antes do início: reembolso total menos EUR 55). 21 dias antes: retenção de 25% da fatura; 20 a 8 dias: 50%; 7 dias ou menos, ou no-show: sem reembolso. Recusa de visto: reembolso do valor bruto menos taxa de registro, taxa de processamento de visto e encargos bancários. Taxas administrativas de assistência a visto não sao devolvidas se o visto for recusado. Sem reembolso em caso de expulsão. Adiamentos: o 1o e gratuito, os seguintes custam EUR 30. Depósito de danos e reembolsável.", "entry_level": "A2/B1", "lesson_minutes": 45, "source": "planilha-2026-09"}'::jsonb);
    insert into product_content (product_id, locale, description_html, highlights) values (v_new,'pt-BR','<p>Combinação de General English (20 aulas em grupo por semana) com English for Aviation (5 aulas individuais por semana), totalizando 25 aulas semanais.</p><p>Segunda a sexta: General English Standard 09:15-10:45 e 11:15-12:45 (20 lições de 45 min) + 5 lições individuais de ESP em horário flexível (segunda a sábado). Cursos de 1 a 7 semanas tem aulas garantidas pela manhã; a partir de 8 semanas pode haver double-banking.</p>','["20 aulas de General English em grupo (09:15–12:45)", "5 aulas individuais da área profissional", "Análise de necessidades no primeiro dia", "Duração de 1 a 11 semanas"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','General English 20 + English for Aviation','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,450,0);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,8,425,1);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_new);
    insert into fee_product (fee_id, product_id) values (v_fee, v_new);
    insert into fee_product (fee_id, product_id) select f.id, v_new from fee f where f.campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and f.fee_type='registration' and f.archived_at is null limit 1;
  end if;

  if not exists (select 1 from price_template_product l join price_template t on t.id=l.price_template_id where l.product_id='952ee862-c699-5bfd-a9bc-0ef871449ddc' and t.status='active') then
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','English for Childcare — 5 aulas individuais/semana','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,200,0);
    insert into price_template_product (price_template_id, product_id) values (v_tpl,'952ee862-c699-5bfd-a9bc-0ef871449ddc');
    update product set visibility='quotable', min_duration=1, max_duration=52, updated_at=now() where id='952ee862-c699-5bfd-a9bc-0ef871449ddc';
  end if;
  insert into fee_product (fee_id, product_id) values (v_fee,'952ee862-c699-5bfd-a9bc-0ef871449ddc') on conflict do nothing;

  select id into v_new from product where campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and kind='program' and attributes->>'slug'='bels-st-pauls-bay-malta-general-english-20-english-for-childcare' and archived_at is null;
  if v_new is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','program','General English 20 + English for Childcare','supplier','quotable','active','week',1,11,'{"seed": "planilha-2026-09", "slug": "bels-st-pauls-bay-malta-general-english-20-english-for-childcare", "course_type": "english-for-specific-purposes", "base_product_slug": "bels-gozo-malta-english-for-childcare"}'::jsonb) returning id into v_new;
    insert into program_detail (product_id, education_type, language, delivery_method, lessons_per_week, hours_per_week, timetable) values (v_new,'english-for-specific-purposes','English','in_person',25,18.75,'{"start_frequency": "Semanal - início em qualquer segunda-feira (BELS FAQ); estadia mínima de 1 semana.", "class_schedule": "Segunda a sexta: General English Standard 09:15-10:45 e 11:15-12:45 (20 lições de 45 min) + 5 lições individuais de ESP em horário flexível (segunda a sábado). Cursos de 1 a 7 semanas tem aulas garantidas pela manhã; a partir de 8 semanas pode haver double-banking.", "non_refundable_fees": "Taxa de inscrição/administrativa de EUR 55 não reembolsável em qualquer cancelamento (até 22 dias antes do início: reembolso total menos EUR 55). 21 dias antes: retenção de 25% da fatura; 20 a 8 dias: 50%; 7 dias ou menos, ou no-show: sem reembolso. Recusa de visto: reembolso do valor bruto menos taxa de registro, taxa de processamento de visto e encargos bancários. Taxas administrativas de assistência a visto não sao devolvidas se o visto for recusado. Sem reembolso em caso de expulsão. Adiamentos: o 1o e gratuito, os seguintes custam EUR 30. Depósito de danos e reembolsável.", "entry_level": "A2/B1", "lesson_minutes": 45, "source": "planilha-2026-09"}'::jsonb);
    insert into product_content (product_id, locale, description_html, highlights) values (v_new,'pt-BR','<p>Combinação de General English (20 aulas em grupo por semana) com English for Childcare (5 aulas individuais por semana), totalizando 25 aulas semanais.</p><p>Segunda a sexta: General English Standard 09:15-10:45 e 11:15-12:45 (20 lições de 45 min) + 5 lições individuais de ESP em horário flexível (segunda a sábado). Cursos de 1 a 7 semanas tem aulas garantidas pela manhã; a partir de 8 semanas pode haver double-banking.</p>','["20 aulas de General English em grupo (09:15–12:45)", "5 aulas individuais da área profissional", "Análise de necessidades no primeiro dia", "Duração de 1 a 11 semanas"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','General English 20 + English for Childcare','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,450,0);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,8,425,1);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_new);
    insert into fee_product (fee_id, product_id) values (v_fee, v_new);
    insert into fee_product (fee_id, product_id) select f.id, v_new from fee f where f.campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and f.fee_type='registration' and f.archived_at is null limit 1;
  end if;

  if not exists (select 1 from price_template_product l join price_template t on t.id=l.price_template_id where l.product_id='b04a11b9-4458-51b9-842e-3e618449359f' and t.status='active') then
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','English for Construction — 5 aulas individuais/semana','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,200,0);
    insert into price_template_product (price_template_id, product_id) values (v_tpl,'b04a11b9-4458-51b9-842e-3e618449359f');
    update product set visibility='quotable', min_duration=1, max_duration=52, updated_at=now() where id='b04a11b9-4458-51b9-842e-3e618449359f';
  end if;
  insert into fee_product (fee_id, product_id) values (v_fee,'b04a11b9-4458-51b9-842e-3e618449359f') on conflict do nothing;

  select id into v_new from product where campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and kind='program' and attributes->>'slug'='bels-st-pauls-bay-malta-general-english-20-english-for-construction' and archived_at is null;
  if v_new is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','program','General English 20 + English for Construction','supplier','quotable','active','week',1,11,'{"seed": "planilha-2026-09", "slug": "bels-st-pauls-bay-malta-general-english-20-english-for-construction", "course_type": "english-for-specific-purposes", "base_product_slug": "bels-gozo-malta-english-for-construction"}'::jsonb) returning id into v_new;
    insert into program_detail (product_id, education_type, language, delivery_method, lessons_per_week, hours_per_week, timetable) values (v_new,'english-for-specific-purposes','English','in_person',25,18.75,'{"start_frequency": "Semanal - início em qualquer segunda-feira (BELS FAQ); estadia mínima de 1 semana.", "class_schedule": "Segunda a sexta: General English Standard 09:15-10:45 e 11:15-12:45 (20 lições de 45 min) + 5 lições individuais de ESP em horário flexível (segunda a sábado). Cursos de 1 a 7 semanas tem aulas garantidas pela manhã; a partir de 8 semanas pode haver double-banking.", "non_refundable_fees": "Taxa de inscrição/administrativa de EUR 55 não reembolsável em qualquer cancelamento (até 22 dias antes do início: reembolso total menos EUR 55). 21 dias antes: retenção de 25% da fatura; 20 a 8 dias: 50%; 7 dias ou menos, ou no-show: sem reembolso. Recusa de visto: reembolso do valor bruto menos taxa de registro, taxa de processamento de visto e encargos bancários. Taxas administrativas de assistência a visto não sao devolvidas se o visto for recusado. Sem reembolso em caso de expulsão. Adiamentos: o 1o e gratuito, os seguintes custam EUR 30. Depósito de danos e reembolsável.", "entry_level": "A2/B1", "lesson_minutes": 45, "source": "planilha-2026-09"}'::jsonb);
    insert into product_content (product_id, locale, description_html, highlights) values (v_new,'pt-BR','<p>Combinação de General English (20 aulas em grupo por semana) com English for Construction (5 aulas individuais por semana), totalizando 25 aulas semanais.</p><p>Segunda a sexta: General English Standard 09:15-10:45 e 11:15-12:45 (20 lições de 45 min) + 5 lições individuais de ESP em horário flexível (segunda a sábado). Cursos de 1 a 7 semanas tem aulas garantidas pela manhã; a partir de 8 semanas pode haver double-banking.</p>','["20 aulas de General English em grupo (09:15–12:45)", "5 aulas individuais da área profissional", "Análise de necessidades no primeiro dia", "Duração de 1 a 11 semanas"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','General English 20 + English for Construction','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,450,0);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,8,425,1);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_new);
    insert into fee_product (fee_id, product_id) values (v_fee, v_new);
    insert into fee_product (fee_id, product_id) select f.id, v_new from fee f where f.campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and f.fee_type='registration' and f.archived_at is null limit 1;
  end if;

  if not exists (select 1 from price_template_product l join price_template t on t.id=l.price_template_id where l.product_id='682dae27-ef4b-5b20-8e35-3db4526f89be' and t.status='active') then
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','English for Customer Service — 5 aulas individuais/semana','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,200,0);
    insert into price_template_product (price_template_id, product_id) values (v_tpl,'682dae27-ef4b-5b20-8e35-3db4526f89be');
    update product set visibility='quotable', min_duration=1, max_duration=52, updated_at=now() where id='682dae27-ef4b-5b20-8e35-3db4526f89be';
  end if;
  insert into fee_product (fee_id, product_id) values (v_fee,'682dae27-ef4b-5b20-8e35-3db4526f89be') on conflict do nothing;

  select id into v_new from product where campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and kind='program' and attributes->>'slug'='bels-st-pauls-bay-malta-general-english-20-english-for-customer-service' and archived_at is null;
  if v_new is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','program','General English 20 + English for Customer Service','supplier','quotable','active','week',1,11,'{"seed": "planilha-2026-09", "slug": "bels-st-pauls-bay-malta-general-english-20-english-for-customer-service", "course_type": "english-for-specific-purposes", "base_product_slug": "bels-gozo-malta-english-for-customer-service"}'::jsonb) returning id into v_new;
    insert into program_detail (product_id, education_type, language, delivery_method, lessons_per_week, hours_per_week, timetable) values (v_new,'english-for-specific-purposes','English','in_person',25,18.75,'{"start_frequency": "Semanal - início em qualquer segunda-feira (BELS FAQ); estadia mínima de 1 semana.", "class_schedule": "Segunda a sexta: General English Standard 09:15-10:45 e 11:15-12:45 (20 lições de 45 min) + 5 lições individuais de ESP em horário flexível (segunda a sábado). Cursos de 1 a 7 semanas tem aulas garantidas pela manhã; a partir de 8 semanas pode haver double-banking.", "non_refundable_fees": "Taxa de inscrição/administrativa de EUR 55 não reembolsável em qualquer cancelamento (até 22 dias antes do início: reembolso total menos EUR 55). 21 dias antes: retenção de 25% da fatura; 20 a 8 dias: 50%; 7 dias ou menos, ou no-show: sem reembolso. Recusa de visto: reembolso do valor bruto menos taxa de registro, taxa de processamento de visto e encargos bancários. Taxas administrativas de assistência a visto não sao devolvidas se o visto for recusado. Sem reembolso em caso de expulsão. Adiamentos: o 1o e gratuito, os seguintes custam EUR 30. Depósito de danos e reembolsável.", "entry_level": "A2/B1", "lesson_minutes": 45, "source": "planilha-2026-09"}'::jsonb);
    insert into product_content (product_id, locale, description_html, highlights) values (v_new,'pt-BR','<p>Combinação de General English (20 aulas em grupo por semana) com English for Customer Service (5 aulas individuais por semana), totalizando 25 aulas semanais.</p><p>Segunda a sexta: General English Standard 09:15-10:45 e 11:15-12:45 (20 lições de 45 min) + 5 lições individuais de ESP em horário flexível (segunda a sábado). Cursos de 1 a 7 semanas tem aulas garantidas pela manhã; a partir de 8 semanas pode haver double-banking.</p>','["20 aulas de General English em grupo (09:15–12:45)", "5 aulas individuais da área profissional", "Análise de necessidades no primeiro dia", "Duração de 1 a 11 semanas"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','General English 20 + English for Customer Service','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,450,0);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,8,425,1);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_new);
    insert into fee_product (fee_id, product_id) values (v_fee, v_new);
    insert into fee_product (fee_id, product_id) select f.id, v_new from fee f where f.campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and f.fee_type='registration' and f.archived_at is null limit 1;
  end if;
end $$;