do $$ declare v_pid uuid; v_tid uuid; v_tpl uuid; v_fee uuid; v_new uuid; begin
  select tenant_id into v_tid from campus where id='cea43266-51db-5e14-8c4b-b4f24611d620';
  select id into v_fee from fee where campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and fee_type='material' and archived_at is null and name='Material didático' limit 1;

  if not exists (select 1 from price_template_product l join price_template t on t.id=l.price_template_id where l.product_id='ff9ba336-01a5-59af-b09c-340a7c61fe1e' and t.status='active') then
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','English for Engireeing — 5 aulas individuais/semana','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,200,0);
    insert into price_template_product (price_template_id, product_id) values (v_tpl,'ff9ba336-01a5-59af-b09c-340a7c61fe1e');
    update product set visibility='quotable', min_duration=1, max_duration=52, updated_at=now() where id='ff9ba336-01a5-59af-b09c-340a7c61fe1e';
  end if;
  insert into fee_product (fee_id, product_id) values (v_fee,'ff9ba336-01a5-59af-b09c-340a7c61fe1e') on conflict do nothing;

  select id into v_new from product where campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and kind='program' and attributes->>'slug'='bels-st-pauls-bay-malta-general-english-20-english-for-engireeing' and archived_at is null;
  if v_new is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','program','General English 20 + English for Engireeing','supplier','quotable','active','week',1,11,'{"seed": "planilha-2026-09", "slug": "bels-st-pauls-bay-malta-general-english-20-english-for-engireeing", "course_type": "english-for-specific-purposes", "base_product_slug": "bels-gozo-malta-english-for-engireeing"}'::jsonb) returning id into v_new;
    insert into program_detail (product_id, education_type, language, delivery_method, lessons_per_week, hours_per_week, timetable) values (v_new,'english-for-specific-purposes','English','in_person',25,18.75,'{"start_frequency": "Semanal - início em qualquer segunda-feira (BELS FAQ); estadia mínima de 1 semana.", "class_schedule": "Segunda a sexta: General English Standard 09:15-10:45 e 11:15-12:45 (20 lições de 45 min) + 5 lições individuais de ESP em horário flexível (segunda a sábado). Cursos de 1 a 7 semanas tem aulas garantidas pela manhã; a partir de 8 semanas pode haver double-banking.", "non_refundable_fees": "Taxa de inscrição/administrativa de EUR 55 não reembolsável em qualquer cancelamento (até 22 dias antes do início: reembolso total menos EUR 55). 21 dias antes: retenção de 25% da fatura; 20 a 8 dias: 50%; 7 dias ou menos, ou no-show: sem reembolso. Recusa de visto: reembolso do valor bruto menos taxa de registro, taxa de processamento de visto e encargos bancários. Taxas administrativas de assistência a visto não sao devolvidas se o visto for recusado. Sem reembolso em caso de expulsão. Adiamentos: o 1o e gratuito, os seguintes custam EUR 30. Depósito de danos e reembolsável.", "entry_level": "A2/B1", "lesson_minutes": 45, "source": "planilha-2026-09"}'::jsonb);
    insert into product_content (product_id, locale, description_html, highlights) values (v_new,'pt-BR','<p>Combinação de General English (20 aulas em grupo por semana) com English for Engireeing (5 aulas individuais por semana), totalizando 25 aulas semanais.</p><p>Segunda a sexta: General English Standard 09:15-10:45 e 11:15-12:45 (20 lições de 45 min) + 5 lições individuais de ESP em horário flexível (segunda a sábado). Cursos de 1 a 7 semanas tem aulas garantidas pela manhã; a partir de 8 semanas pode haver double-banking.</p>','["20 aulas de General English em grupo (09:15–12:45)", "5 aulas individuais da área profissional", "Análise de necessidades no primeiro dia", "Duração de 1 a 11 semanas"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','General English 20 + English for Engireeing','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,450,0);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,8,425,1);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_new);
    insert into fee_product (fee_id, product_id) values (v_fee, v_new);
    insert into fee_product (fee_id, product_id) select f.id, v_new from fee f where f.campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and f.fee_type='registration' and f.archived_at is null limit 1;
  end if;

  if not exists (select 1 from price_template_product l join price_template t on t.id=l.price_template_id where l.product_id='977ebd10-a608-54fd-bf11-80794bbd1609' and t.status='active') then
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','English for Food and Beverage — 5 aulas individuais/semana','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,200,0);
    insert into price_template_product (price_template_id, product_id) values (v_tpl,'977ebd10-a608-54fd-bf11-80794bbd1609');
    update product set visibility='quotable', min_duration=1, max_duration=52, updated_at=now() where id='977ebd10-a608-54fd-bf11-80794bbd1609';
  end if;
  insert into fee_product (fee_id, product_id) values (v_fee,'977ebd10-a608-54fd-bf11-80794bbd1609') on conflict do nothing;

  select id into v_new from product where campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and kind='program' and attributes->>'slug'='bels-st-pauls-bay-malta-general-english-20-english-for-food-and-beverage' and archived_at is null;
  if v_new is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','program','General English 20 + English for Food and Beverage','supplier','quotable','active','week',1,11,'{"seed": "planilha-2026-09", "slug": "bels-st-pauls-bay-malta-general-english-20-english-for-food-and-beverage", "course_type": "english-for-specific-purposes", "base_product_slug": "bels-gozo-malta-english-for-food-and-beverage"}'::jsonb) returning id into v_new;
    insert into program_detail (product_id, education_type, language, delivery_method, lessons_per_week, hours_per_week, timetable) values (v_new,'english-for-specific-purposes','English','in_person',25,18.75,'{"start_frequency": "Semanal - início em qualquer segunda-feira (BELS FAQ); estadia mínima de 1 semana.", "class_schedule": "Segunda a sexta: General English Standard 09:15-10:45 e 11:15-12:45 (20 lições de 45 min) + 5 lições individuais de ESP em horário flexível (segunda a sábado). Cursos de 1 a 7 semanas tem aulas garantidas pela manhã; a partir de 8 semanas pode haver double-banking.", "non_refundable_fees": "Taxa de inscrição/administrativa de EUR 55 não reembolsável em qualquer cancelamento (até 22 dias antes do início: reembolso total menos EUR 55). 21 dias antes: retenção de 25% da fatura; 20 a 8 dias: 50%; 7 dias ou menos, ou no-show: sem reembolso. Recusa de visto: reembolso do valor bruto menos taxa de registro, taxa de processamento de visto e encargos bancários. Taxas administrativas de assistência a visto não sao devolvidas se o visto for recusado. Sem reembolso em caso de expulsão. Adiamentos: o 1o e gratuito, os seguintes custam EUR 30. Depósito de danos e reembolsável.", "entry_level": "A2/B1", "lesson_minutes": 45, "source": "planilha-2026-09"}'::jsonb);
    insert into product_content (product_id, locale, description_html, highlights) values (v_new,'pt-BR','<p>Combinação de General English (20 aulas em grupo por semana) com English for Food and Beverage (5 aulas individuais por semana), totalizando 25 aulas semanais.</p><p>Segunda a sexta: General English Standard 09:15-10:45 e 11:15-12:45 (20 lições de 45 min) + 5 lições individuais de ESP em horário flexível (segunda a sábado). Cursos de 1 a 7 semanas tem aulas garantidas pela manhã; a partir de 8 semanas pode haver double-banking.</p>','["20 aulas de General English em grupo (09:15–12:45)", "5 aulas individuais da área profissional", "Análise de necessidades no primeiro dia", "Duração de 1 a 11 semanas"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','General English 20 + English for Food and Beverage','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,450,0);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,8,425,1);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_new);
    insert into fee_product (fee_id, product_id) values (v_fee, v_new);
    insert into fee_product (fee_id, product_id) select f.id, v_new from fee f where f.campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and f.fee_type='registration' and f.archived_at is null limit 1;
  end if;

  if not exists (select 1 from price_template_product l join price_template t on t.id=l.price_template_id where l.product_id='5eee54c1-387c-5835-9de6-f15d187eed01' and t.status='active') then
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','English for Human Resources — 5 aulas individuais/semana','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,200,0);
    insert into price_template_product (price_template_id, product_id) values (v_tpl,'5eee54c1-387c-5835-9de6-f15d187eed01');
    update product set visibility='quotable', min_duration=1, max_duration=52, updated_at=now() where id='5eee54c1-387c-5835-9de6-f15d187eed01';
  end if;
  insert into fee_product (fee_id, product_id) values (v_fee,'5eee54c1-387c-5835-9de6-f15d187eed01') on conflict do nothing;

  select id into v_new from product where campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and kind='program' and attributes->>'slug'='bels-st-pauls-bay-malta-general-english-20-english-for-human-resources' and archived_at is null;
  if v_new is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','program','General English 20 + English for Human Resources','supplier','quotable','active','week',1,11,'{"seed": "planilha-2026-09", "slug": "bels-st-pauls-bay-malta-general-english-20-english-for-human-resources", "course_type": "english-for-specific-purposes", "base_product_slug": "bels-gozo-malta-english-for-human-resources"}'::jsonb) returning id into v_new;
    insert into program_detail (product_id, education_type, language, delivery_method, lessons_per_week, hours_per_week, timetable) values (v_new,'english-for-specific-purposes','English','in_person',25,18.75,'{"start_frequency": "Semanal - início em qualquer segunda-feira (BELS FAQ); estadia mínima de 1 semana.", "class_schedule": "Segunda a sexta: General English Standard 09:15-10:45 e 11:15-12:45 (20 lições de 45 min) + 5 lições individuais de ESP em horário flexível (segunda a sábado). Cursos de 1 a 7 semanas tem aulas garantidas pela manhã; a partir de 8 semanas pode haver double-banking.", "non_refundable_fees": "Taxa de inscrição/administrativa de EUR 55 não reembolsável em qualquer cancelamento (até 22 dias antes do início: reembolso total menos EUR 55). 21 dias antes: retenção de 25% da fatura; 20 a 8 dias: 50%; 7 dias ou menos, ou no-show: sem reembolso. Recusa de visto: reembolso do valor bruto menos taxa de registro, taxa de processamento de visto e encargos bancários. Taxas administrativas de assistência a visto não sao devolvidas se o visto for recusado. Sem reembolso em caso de expulsão. Adiamentos: o 1o e gratuito, os seguintes custam EUR 30. Depósito de danos e reembolsável.", "entry_level": "A1/B2", "lesson_minutes": 45, "source": "planilha-2026-09"}'::jsonb);
    insert into product_content (product_id, locale, description_html, highlights) values (v_new,'pt-BR','<p>Combinação de General English (20 aulas em grupo por semana) com English for Human Resources (5 aulas individuais por semana), totalizando 25 aulas semanais.</p><p>Segunda a sexta: General English Standard 09:15-10:45 e 11:15-12:45 (20 lições de 45 min) + 5 lições individuais de ESP em horário flexível (segunda a sábado). Cursos de 1 a 7 semanas tem aulas garantidas pela manhã; a partir de 8 semanas pode haver double-banking.</p>','["20 aulas de General English em grupo (09:15–12:45)", "5 aulas individuais da área profissional", "Análise de necessidades no primeiro dia", "Duração de 1 a 11 semanas"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','General English 20 + English for Human Resources','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,450,0);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,8,425,1);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_new);
    insert into fee_product (fee_id, product_id) values (v_fee, v_new);
    insert into fee_product (fee_id, product_id) select f.id, v_new from fee f where f.campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and f.fee_type='registration' and f.archived_at is null limit 1;
  end if;

  if not exists (select 1 from price_template_product l join price_template t on t.id=l.price_template_id where l.product_id='165fad20-6340-5c33-870c-4dc53e13fa99' and t.status='active') then
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','English for Information Technology — 5 aulas individuais/semana','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,200,0);
    insert into price_template_product (price_template_id, product_id) values (v_tpl,'165fad20-6340-5c33-870c-4dc53e13fa99');
    update product set visibility='quotable', min_duration=1, max_duration=52, updated_at=now() where id='165fad20-6340-5c33-870c-4dc53e13fa99';
  end if;
  insert into fee_product (fee_id, product_id) values (v_fee,'165fad20-6340-5c33-870c-4dc53e13fa99') on conflict do nothing;

  select id into v_new from product where campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and kind='program' and attributes->>'slug'='bels-st-pauls-bay-malta-general-english-20-english-for-information-technology' and archived_at is null;
  if v_new is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','program','General English 20 + English for Information Technology','supplier','quotable','active','week',1,11,'{"seed": "planilha-2026-09", "slug": "bels-st-pauls-bay-malta-general-english-20-english-for-information-technology", "course_type": "english-for-specific-purposes", "base_product_slug": "bels-gozo-malta-english-for-information-technology"}'::jsonb) returning id into v_new;
    insert into program_detail (product_id, education_type, language, delivery_method, lessons_per_week, hours_per_week, timetable) values (v_new,'english-for-specific-purposes','English','in_person',25,18.75,'{"start_frequency": "Semanal - início em qualquer segunda-feira (BELS FAQ); estadia mínima de 1 semana.", "class_schedule": "Segunda a sexta: General English Standard 09:15-10:45 e 11:15-12:45 (20 lições de 45 min) + 5 lições individuais de ESP em horário flexível (segunda a sábado). Cursos de 1 a 7 semanas tem aulas garantidas pela manhã; a partir de 8 semanas pode haver double-banking.", "non_refundable_fees": "Taxa de inscrição/administrativa de EUR 55 não reembolsável em qualquer cancelamento (até 22 dias antes do início: reembolso total menos EUR 55). 21 dias antes: retenção de 25% da fatura; 20 a 8 dias: 50%; 7 dias ou menos, ou no-show: sem reembolso. Recusa de visto: reembolso do valor bruto menos taxa de registro, taxa de processamento de visto e encargos bancários. Taxas administrativas de assistência a visto não sao devolvidas se o visto for recusado. Sem reembolso em caso de expulsão. Adiamentos: o 1o e gratuito, os seguintes custam EUR 30. Depósito de danos e reembolsável.", "entry_level": "A2", "lesson_minutes": 45, "source": "planilha-2026-09"}'::jsonb);
    insert into product_content (product_id, locale, description_html, highlights) values (v_new,'pt-BR','<p>Combinação de General English (20 aulas em grupo por semana) com English for Information Technology (5 aulas individuais por semana), totalizando 25 aulas semanais.</p><p>Segunda a sexta: General English Standard 09:15-10:45 e 11:15-12:45 (20 lições de 45 min) + 5 lições individuais de ESP em horário flexível (segunda a sábado). Cursos de 1 a 7 semanas tem aulas garantidas pela manhã; a partir de 8 semanas pode haver double-banking.</p>','["20 aulas de General English em grupo (09:15–12:45)", "5 aulas individuais da área profissional", "Análise de necessidades no primeiro dia", "Duração de 1 a 11 semanas"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','General English 20 + English for Information Technology','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,450,0);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,8,425,1);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_new);
    insert into fee_product (fee_id, product_id) values (v_fee, v_new);
    insert into fee_product (fee_id, product_id) select f.id, v_new from fee f where f.campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and f.fee_type='registration' and f.archived_at is null limit 1;
  end if;

  if not exists (select 1 from price_template_product l join price_template t on t.id=l.price_template_id where l.product_id='ac603983-d848-573b-8ad6-1b55c1d125bf' and t.status='active') then
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','English for Insurance Companies — 5 aulas individuais/semana','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,200,0);
    insert into price_template_product (price_template_id, product_id) values (v_tpl,'ac603983-d848-573b-8ad6-1b55c1d125bf');
    update product set visibility='quotable', min_duration=1, max_duration=52, updated_at=now() where id='ac603983-d848-573b-8ad6-1b55c1d125bf';
  end if;
  insert into fee_product (fee_id, product_id) values (v_fee,'ac603983-d848-573b-8ad6-1b55c1d125bf') on conflict do nothing;

  select id into v_new from product where campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and kind='program' and attributes->>'slug'='bels-st-pauls-bay-malta-general-english-20-english-for-insurance-companies' and archived_at is null;
  if v_new is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','program','General English 20 + English for Insurance Companies','supplier','quotable','active','week',1,11,'{"seed": "planilha-2026-09", "slug": "bels-st-pauls-bay-malta-general-english-20-english-for-insurance-companies", "course_type": "english-for-specific-purposes", "base_product_slug": "bels-gozo-malta-english-for-insurance-companies"}'::jsonb) returning id into v_new;
    insert into program_detail (product_id, education_type, language, delivery_method, lessons_per_week, hours_per_week, timetable) values (v_new,'english-for-specific-purposes','English','in_person',25,18.75,'{"start_frequency": "Semanal - início em qualquer segunda-feira (BELS FAQ); estadia mínima de 1 semana.", "class_schedule": "Segunda a sexta: General English Standard 09:15-10:45 e 11:15-12:45 (20 lições de 45 min) + 5 lições individuais de ESP em horário flexível (segunda a sábado). Cursos de 1 a 7 semanas tem aulas garantidas pela manhã; a partir de 8 semanas pode haver double-banking.", "non_refundable_fees": "Taxa de inscrição/administrativa de EUR 55 não reembolsável em qualquer cancelamento (até 22 dias antes do início: reembolso total menos EUR 55). 21 dias antes: retenção de 25% da fatura; 20 a 8 dias: 50%; 7 dias ou menos, ou no-show: sem reembolso. Recusa de visto: reembolso do valor bruto menos taxa de registro, taxa de processamento de visto e encargos bancários. Taxas administrativas de assistência a visto não sao devolvidas se o visto for recusado. Sem reembolso em caso de expulsão. Adiamentos: o 1o e gratuito, os seguintes custam EUR 30. Depósito de danos e reembolsável.", "entry_level": "A2/B1", "lesson_minutes": 45, "source": "planilha-2026-09"}'::jsonb);
    insert into product_content (product_id, locale, description_html, highlights) values (v_new,'pt-BR','<p>Combinação de General English (20 aulas em grupo por semana) com English for Insurance Companies (5 aulas individuais por semana), totalizando 25 aulas semanais.</p><p>Segunda a sexta: General English Standard 09:15-10:45 e 11:15-12:45 (20 lições de 45 min) + 5 lições individuais de ESP em horário flexível (segunda a sábado). Cursos de 1 a 7 semanas tem aulas garantidas pela manhã; a partir de 8 semanas pode haver double-banking.</p>','["20 aulas de General English em grupo (09:15–12:45)", "5 aulas individuais da área profissional", "Análise de necessidades no primeiro dia", "Duração de 1 a 11 semanas"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','General English 20 + English for Insurance Companies','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,450,0);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,8,425,1);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_new);
    insert into fee_product (fee_id, product_id) values (v_fee, v_new);
    insert into fee_product (fee_id, product_id) select f.id, v_new from fee f where f.campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and f.fee_type='registration' and f.archived_at is null limit 1;
  end if;

  if not exists (select 1 from price_template_product l join price_template t on t.id=l.price_template_id where l.product_id='3c180bce-afe4-52fa-8796-70ebf0757c1c' and t.status='active') then
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','English for Management — 5 aulas individuais/semana','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,200,0);
    insert into price_template_product (price_template_id, product_id) values (v_tpl,'3c180bce-afe4-52fa-8796-70ebf0757c1c');
    update product set visibility='quotable', min_duration=1, max_duration=52, updated_at=now() where id='3c180bce-afe4-52fa-8796-70ebf0757c1c';
  end if;
  insert into fee_product (fee_id, product_id) values (v_fee,'3c180bce-afe4-52fa-8796-70ebf0757c1c') on conflict do nothing;

  select id into v_new from product where campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and kind='program' and attributes->>'slug'='bels-st-pauls-bay-malta-general-english-20-english-for-management' and archived_at is null;
  if v_new is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','program','General English 20 + English for Management','supplier','quotable','active','week',1,11,'{"seed": "planilha-2026-09", "slug": "bels-st-pauls-bay-malta-general-english-20-english-for-management", "course_type": "english-for-specific-purposes", "base_product_slug": "bels-gozo-malta-english-for-management"}'::jsonb) returning id into v_new;
    insert into program_detail (product_id, education_type, language, delivery_method, lessons_per_week, hours_per_week, timetable) values (v_new,'english-for-specific-purposes','English','in_person',25,18.75,'{"start_frequency": "Semanal - início em qualquer segunda-feira (BELS FAQ); estadia mínima de 1 semana.", "class_schedule": "Segunda a sexta: General English Standard 09:15-10:45 e 11:15-12:45 (20 lições de 45 min) + 5 lições individuais de ESP em horário flexível (segunda a sábado). Cursos de 1 a 7 semanas tem aulas garantidas pela manhã; a partir de 8 semanas pode haver double-banking.", "non_refundable_fees": "Taxa de inscrição/administrativa de EUR 55 não reembolsável em qualquer cancelamento (até 22 dias antes do início: reembolso total menos EUR 55). 21 dias antes: retenção de 25% da fatura; 20 a 8 dias: 50%; 7 dias ou menos, ou no-show: sem reembolso. Recusa de visto: reembolso do valor bruto menos taxa de registro, taxa de processamento de visto e encargos bancários. Taxas administrativas de assistência a visto não sao devolvidas se o visto for recusado. Sem reembolso em caso de expulsão. Adiamentos: o 1o e gratuito, os seguintes custam EUR 30. Depósito de danos e reembolsável.", "entry_level": "A2/B1", "lesson_minutes": 45, "source": "planilha-2026-09"}'::jsonb);
    insert into product_content (product_id, locale, description_html, highlights) values (v_new,'pt-BR','<p>Combinação de General English (20 aulas em grupo por semana) com English for Management (5 aulas individuais por semana), totalizando 25 aulas semanais.</p><p>Segunda a sexta: General English Standard 09:15-10:45 e 11:15-12:45 (20 lições de 45 min) + 5 lições individuais de ESP em horário flexível (segunda a sábado). Cursos de 1 a 7 semanas tem aulas garantidas pela manhã; a partir de 8 semanas pode haver double-banking.</p>','["20 aulas de General English em grupo (09:15–12:45)", "5 aulas individuais da área profissional", "Análise de necessidades no primeiro dia", "Duração de 1 a 11 semanas"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','General English 20 + English for Management','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,450,0);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,8,425,1);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_new);
    insert into fee_product (fee_id, product_id) values (v_fee, v_new);
    insert into fee_product (fee_id, product_id) select f.id, v_new from fee f where f.campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and f.fee_type='registration' and f.archived_at is null limit 1;
  end if;
end $$;