do $$ declare v_pid uuid; v_tid uuid; v_tpl uuid; v_fee uuid; v_new uuid; begin
  select tenant_id into v_tid from campus where id='cea43266-51db-5e14-8c4b-b4f24611d620';
  select id into v_fee from fee where campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and fee_type='material' and archived_at is null and name='Material didático' limit 1;

  if not exists (select 1 from price_template_product l join price_template t on t.id=l.price_template_id where l.product_id='e8fb23d2-510a-50cd-bb6a-0a6a3d6507ff' and t.status='active') then
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','English for Maritime — 5 aulas individuais/semana','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,200,0);
    insert into price_template_product (price_template_id, product_id) values (v_tpl,'e8fb23d2-510a-50cd-bb6a-0a6a3d6507ff');
    update product set visibility='quotable', min_duration=1, max_duration=52, updated_at=now() where id='e8fb23d2-510a-50cd-bb6a-0a6a3d6507ff';
  end if;
  insert into fee_product (fee_id, product_id) values (v_fee,'e8fb23d2-510a-50cd-bb6a-0a6a3d6507ff') on conflict do nothing;

  select id into v_new from product where campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and kind='program' and attributes->>'slug'='bels-st-pauls-bay-malta-general-english-20-english-for-maritime' and archived_at is null;
  if v_new is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','program','General English 20 + English for Maritime','supplier','quotable','active','week',1,11,'{"seed": "planilha-2026-09", "slug": "bels-st-pauls-bay-malta-general-english-20-english-for-maritime", "course_type": "english-for-specific-purposes", "base_product_slug": "bels-gozo-malta-english-for-maritime"}'::jsonb) returning id into v_new;
    insert into program_detail (product_id, education_type, language, delivery_method, lessons_per_week, hours_per_week, timetable) values (v_new,'english-for-specific-purposes','English','in_person',25,18.75,'{"start_frequency": "Semanal - início em qualquer segunda-feira (BELS FAQ); estadia mínima de 1 semana.", "class_schedule": "Segunda a sexta: General English Standard 09:15-10:45 e 11:15-12:45 (20 lições de 45 min) + 5 lições individuais de ESP em horário flexível (segunda a sábado). Cursos de 1 a 7 semanas tem aulas garantidas pela manhã; a partir de 8 semanas pode haver double-banking.", "non_refundable_fees": "Taxa de inscrição/administrativa de EUR 55 não reembolsável em qualquer cancelamento (até 22 dias antes do início: reembolso total menos EUR 55). 21 dias antes: retenção de 25% da fatura; 20 a 8 dias: 50%; 7 dias ou menos, ou no-show: sem reembolso. Recusa de visto: reembolso do valor bruto menos taxa de registro, taxa de processamento de visto e encargos bancários. Taxas administrativas de assistência a visto não sao devolvidas se o visto for recusado. Sem reembolso em caso de expulsão. Adiamentos: o 1o e gratuito, os seguintes custam EUR 30. Depósito de danos e reembolsável.", "entry_level": "A2", "lesson_minutes": 45, "source": "planilha-2026-09"}'::jsonb);
    insert into product_content (product_id, locale, description_html, highlights) values (v_new,'pt-BR','<p>Combinação de General English (20 aulas em grupo por semana) com English for Maritime (5 aulas individuais por semana), totalizando 25 aulas semanais.</p><p>Segunda a sexta: General English Standard 09:15-10:45 e 11:15-12:45 (20 lições de 45 min) + 5 lições individuais de ESP em horário flexível (segunda a sábado). Cursos de 1 a 7 semanas tem aulas garantidas pela manhã; a partir de 8 semanas pode haver double-banking.</p>','["20 aulas de General English em grupo (09:15–12:45)", "5 aulas individuais da área profissional", "Análise de necessidades no primeiro dia", "Duração de 1 a 11 semanas"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','General English 20 + English for Maritime','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,450,0);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,8,425,1);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_new);
    insert into fee_product (fee_id, product_id) values (v_fee, v_new);
    insert into fee_product (fee_id, product_id) select f.id, v_new from fee f where f.campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and f.fee_type='registration' and f.archived_at is null limit 1;
  end if;

  if not exists (select 1 from price_template_product l join price_template t on t.id=l.price_template_id where l.product_id='9376b323-4b3d-5f31-a7b5-2094722a422e' and t.status='active') then
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','English for Marketing and Sales — 5 aulas individuais/semana','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,200,0);
    insert into price_template_product (price_template_id, product_id) values (v_tpl,'9376b323-4b3d-5f31-a7b5-2094722a422e');
    update product set visibility='quotable', min_duration=1, max_duration=52, updated_at=now() where id='9376b323-4b3d-5f31-a7b5-2094722a422e';
  end if;
  insert into fee_product (fee_id, product_id) values (v_fee,'9376b323-4b3d-5f31-a7b5-2094722a422e') on conflict do nothing;

  select id into v_new from product where campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and kind='program' and attributes->>'slug'='bels-st-pauls-bay-malta-general-english-20-english-for-marketing-and-sales' and archived_at is null;
  if v_new is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','program','General English 20 + English for Marketing and Sales','supplier','quotable','active','week',1,11,'{"seed": "planilha-2026-09", "slug": "bels-st-pauls-bay-malta-general-english-20-english-for-marketing-and-sales", "course_type": "english-for-specific-purposes", "base_product_slug": "bels-gozo-malta-english-for-marketing-and-sales"}'::jsonb) returning id into v_new;
    insert into program_detail (product_id, education_type, language, delivery_method, lessons_per_week, hours_per_week, timetable) values (v_new,'english-for-specific-purposes','English','in_person',25,18.75,'{"start_frequency": "Semanal - início em qualquer segunda-feira (BELS FAQ); estadia mínima de 1 semana.", "class_schedule": "Segunda a sexta: General English Standard 09:15-10:45 e 11:15-12:45 (20 lições de 45 min) + 5 lições individuais de ESP em horário flexível (segunda a sábado). Cursos de 1 a 7 semanas tem aulas garantidas pela manhã; a partir de 8 semanas pode haver double-banking.", "non_refundable_fees": "Taxa de inscrição/administrativa de EUR 55 não reembolsável em qualquer cancelamento (até 22 dias antes do início: reembolso total menos EUR 55). 21 dias antes: retenção de 25% da fatura; 20 a 8 dias: 50%; 7 dias ou menos, ou no-show: sem reembolso. Recusa de visto: reembolso do valor bruto menos taxa de registro, taxa de processamento de visto e encargos bancários. Taxas administrativas de assistência a visto não sao devolvidas se o visto for recusado. Sem reembolso em caso de expulsão. Adiamentos: o 1o e gratuito, os seguintes custam EUR 30. Depósito de danos e reembolsável.", "entry_level": "A2/B1", "lesson_minutes": 45, "source": "planilha-2026-09"}'::jsonb);
    insert into product_content (product_id, locale, description_html, highlights) values (v_new,'pt-BR','<p>Combinação de General English (20 aulas em grupo por semana) com English for Marketing and Sales (5 aulas individuais por semana), totalizando 25 aulas semanais.</p><p>Segunda a sexta: General English Standard 09:15-10:45 e 11:15-12:45 (20 lições de 45 min) + 5 lições individuais de ESP em horário flexível (segunda a sábado). Cursos de 1 a 7 semanas tem aulas garantidas pela manhã; a partir de 8 semanas pode haver double-banking.</p>','["20 aulas de General English em grupo (09:15–12:45)", "5 aulas individuais da área profissional", "Análise de necessidades no primeiro dia", "Duração de 1 a 11 semanas"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','General English 20 + English for Marketing and Sales','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,450,0);
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,8,425,1);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_new);
    insert into fee_product (fee_id, product_id) values (v_fee, v_new);
    insert into fee_product (fee_id, product_id) select f.id, v_new from fee f where f.campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and f.fee_type='registration' and f.archived_at is null limit 1;
  end if;

  if not exists (select 1 from price_template_product l join price_template t on t.id=l.price_template_id where l.product_id='bc12f48f-9edd-56a9-ac10-99225bedb88c' and t.status='active') then
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','English for Oil and Gas — 5 aulas individuais/semana','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,200,0);
    insert into price_template_product (price_template_id, product_id) values (v_tpl,'bc12f48f-9edd-56a9-ac10-99225bedb88c');
    update product set visibility='quotable', min_duration=1, max_duration=52, updated_at=now() where id='bc12f48f-9edd-56a9-ac10-99225bedb88c';
  end if;
  insert into fee_product (fee_id, product_id) values (v_fee,'bc12f48f-9edd-56a9-ac10-99225bedb88c') on conflict do nothing;

  select id into v_new from product where campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and kind='program' and attributes->>'slug'='bels-st-pauls-bay-malta-general-english-20-english-for-oil-and-gas' and archived_at is null;
  if v_new is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','program','General English 20 + English for Oil and Gas','supplier','quotable','active','week',1,11,'{"seed": "planilha-2026-09", "slug": "bels-st-pauls-bay-malta-general-english-20-english-for-oil-and-gas", "course_type": "english-for-specific-purposes", "base_product_slug": "bels-gozo-malta-english-for-oil-and-gas"}'::jsonb) returning id into v_new;
    insert into program_detail (product_id, education_type, language, delivery_method, lessons_per_week, hours_per_week, timetable) values (v_new,'english-for-specific-purposes','English','in_person',25,18.75,'{"start_frequency": "Semanal - início em qualquer segunda-feira (BELS FAQ); estadia mínima de 1 semana.", "class_schedule": "Segunda a sexta: General English Standard 09:15-10:45 e 11:15-12:45 (20 lições de 45 min) + 5 lições individuais de ESP em horário flexível (segunda a sábado). Cursos de 1 a 7 semanas tem aulas garantidas pela manhã; a partir de 8 semanas pode haver double-banking.", "non_refundable_fees": "Taxa de inscrição/administrativa de EUR 55 não reembolsável em qualquer cancelamento (até 22 dias antes do início: reembolso total menos EUR 55). 21 dias antes: retenção de 25% da fatura; 20 a 8 dias: 50%; 7 dias ou menos, ou no-show: sem reembolso. Recusa de visto: reembolso do valor bruto menos taxa de registro, taxa de processamento de visto e encargos bancários. Taxas administrativas de assistência a visto não sao devolvidas se o visto for recusado. Sem reembolso em caso de expulsão. Adiamentos: o 1o e gratuito, os seguintes custam EUR 30. Depósito de danos e reembolsável.", "entry_level": "A1/B2", "lesson_minutes": 45, "source": "planilha-2026-09"}'::jsonb);
    insert into product_content (product_id, locale, description_html, highlights) values (v_new,'pt-BR','<p>Combinação de General English (20 aulas em grupo por semana) com English for Oil and Gas (5 aulas individuais por semana), totalizando 25 aulas semanais.</p><p>Segunda a sexta: General English Standard 09:15-10:45 e 11:15-12:45 (20 lições de 45 min) + 5 lições individuais de ESP em horário flexível (segunda a sábado). Cursos de 1 a 7 semanas tem aulas garantidas pela manhã; a partir de 8 semanas pode haver double-banking.</p>','["20 aulas de General English em grupo (09:15–12:45)", "5 aulas individuais da área profissional", "Análise de necessidades no primeiro dia", "Duração de 1 a 11 semanas"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','General English 20 + English for Oil and Gas','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,450,0);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_new);
    insert into fee_product (fee_id, product_id) values (v_fee, v_new);
    insert into fee_product (fee_id, product_id) select f.id, v_new from fee f where f.campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and f.fee_type='registration' and f.archived_at is null limit 1;
  end if;

  if not exists (select 1 from price_template_product l join price_template t on t.id=l.price_template_id where l.product_id='e01cc65b-9991-5db1-994f-f294f6276dd5' and t.status='active') then
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','English for Real Estate — 5 aulas individuais/semana','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,200,0);
    insert into price_template_product (price_template_id, product_id) values (v_tpl,'e01cc65b-9991-5db1-994f-f294f6276dd5');
    update product set visibility='quotable', min_duration=1, max_duration=52, updated_at=now() where id='e01cc65b-9991-5db1-994f-f294f6276dd5';
  end if;
  insert into fee_product (fee_id, product_id) values (v_fee,'e01cc65b-9991-5db1-994f-f294f6276dd5') on conflict do nothing;

  select id into v_new from product where campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and kind='program' and attributes->>'slug'='bels-st-pauls-bay-malta-general-english-20-english-for-real-estate' and archived_at is null;
  if v_new is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','program','General English 20 + English for Real Estate','supplier','quotable','active','week',1,11,'{"seed": "planilha-2026-09", "slug": "bels-st-pauls-bay-malta-general-english-20-english-for-real-estate", "course_type": "english-for-specific-purposes", "base_product_slug": "bels-gozo-malta-english-for-real-estate"}'::jsonb) returning id into v_new;
    insert into program_detail (product_id, education_type, language, delivery_method, lessons_per_week, hours_per_week, timetable) values (v_new,'english-for-specific-purposes','English','in_person',25,18.75,'{"start_frequency": "Semanal - início em qualquer segunda-feira (BELS FAQ); estadia mínima de 1 semana.", "class_schedule": "Segunda a sexta: General English Standard 09:15-10:45 e 11:15-12:45 (20 lições de 45 min) + 5 lições individuais de ESP em horário flexível (segunda a sábado). Cursos de 1 a 7 semanas tem aulas garantidas pela manhã; a partir de 8 semanas pode haver double-banking.", "non_refundable_fees": "Taxa de inscrição/administrativa de EUR 55 não reembolsável em qualquer cancelamento (até 22 dias antes do início: reembolso total menos EUR 55). 21 dias antes: retenção de 25% da fatura; 20 a 8 dias: 50%; 7 dias ou menos, ou no-show: sem reembolso. Recusa de visto: reembolso do valor bruto menos taxa de registro, taxa de processamento de visto e encargos bancários. Taxas administrativas de assistência a visto não sao devolvidas se o visto for recusado. Sem reembolso em caso de expulsão. Adiamentos: o 1o e gratuito, os seguintes custam EUR 30. Depósito de danos e reembolsável.", "entry_level": "A2/B1", "lesson_minutes": 45, "source": "planilha-2026-09"}'::jsonb);
    insert into product_content (product_id, locale, description_html, highlights) values (v_new,'pt-BR','<p>Combinação de General English (20 aulas em grupo por semana) com English for Real Estate (5 aulas individuais por semana), totalizando 25 aulas semanais.</p><p>Segunda a sexta: General English Standard 09:15-10:45 e 11:15-12:45 (20 lições de 45 min) + 5 lições individuais de ESP em horário flexível (segunda a sábado). Cursos de 1 a 7 semanas tem aulas garantidas pela manhã; a partir de 8 semanas pode haver double-banking.</p>','["20 aulas de General English em grupo (09:15–12:45)", "5 aulas individuais da área profissional", "Análise de necessidades no primeiro dia", "Duração de 1 a 11 semanas"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','General English 20 + English for Real Estate','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,450,0);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_new);
    insert into fee_product (fee_id, product_id) values (v_fee, v_new);
    insert into fee_product (fee_id, product_id) select f.id, v_new from fee f where f.campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and f.fee_type='registration' and f.archived_at is null limit 1;
  end if;

  if not exists (select 1 from price_template_product l join price_template t on t.id=l.price_template_id where l.product_id='18fc2e83-70d0-5d84-ac6c-07b6bb4de1f4' and t.status='active') then
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','English for Tourism — 5 aulas individuais/semana','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,200,0);
    insert into price_template_product (price_template_id, product_id) values (v_tpl,'18fc2e83-70d0-5d84-ac6c-07b6bb4de1f4');
    update product set visibility='quotable', min_duration=1, max_duration=52, updated_at=now() where id='18fc2e83-70d0-5d84-ac6c-07b6bb4de1f4';
  end if;
  insert into fee_product (fee_id, product_id) values (v_fee,'18fc2e83-70d0-5d84-ac6c-07b6bb4de1f4') on conflict do nothing;

  select id into v_new from product where campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and kind='program' and attributes->>'slug'='bels-st-pauls-bay-malta-general-english-20-english-for-tourism' and archived_at is null;
  if v_new is null then
    insert into product (tenant_id, campus_id, kind, name, source, visibility, status, default_unit, min_duration, max_duration, attributes) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','program','General English 20 + English for Tourism','supplier','quotable','active','week',1,11,'{"seed": "planilha-2026-09", "slug": "bels-st-pauls-bay-malta-general-english-20-english-for-tourism", "course_type": "english-for-specific-purposes", "base_product_slug": "bels-gozo-malta-english-for-tourism"}'::jsonb) returning id into v_new;
    insert into program_detail (product_id, education_type, language, delivery_method, lessons_per_week, hours_per_week, timetable) values (v_new,'english-for-specific-purposes','English','in_person',25,18.75,'{"start_frequency": "Semanal - início em qualquer segunda-feira (BELS FAQ); estadia mínima de 1 semana.", "class_schedule": "Segunda a sexta: General English Standard 09:15-10:45 e 11:15-12:45 (20 lições de 45 min) + 5 lições individuais de ESP em horário flexível (segunda a sábado). Cursos de 1 a 7 semanas tem aulas garantidas pela manhã; a partir de 8 semanas pode haver double-banking.", "non_refundable_fees": "Taxa de inscrição/administrativa de EUR 55 não reembolsável em qualquer cancelamento (até 22 dias antes do início: reembolso total menos EUR 55). 21 dias antes: retenção de 25% da fatura; 20 a 8 dias: 50%; 7 dias ou menos, ou no-show: sem reembolso. Recusa de visto: reembolso do valor bruto menos taxa de registro, taxa de processamento de visto e encargos bancários. Taxas administrativas de assistência a visto não sao devolvidas se o visto for recusado. Sem reembolso em caso de expulsão. Adiamentos: o 1o e gratuito, os seguintes custam EUR 30. Depósito de danos e reembolsável.", "entry_level": "A2/B1", "lesson_minutes": 45, "source": "planilha-2026-09"}'::jsonb);
    insert into product_content (product_id, locale, description_html, highlights) values (v_new,'pt-BR','<p>Combinação de General English (20 aulas em grupo por semana) com English for Tourism (5 aulas individuais por semana), totalizando 25 aulas semanais.</p><p>Segunda a sexta: General English Standard 09:15-10:45 e 11:15-12:45 (20 lições de 45 min) + 5 lições individuais de ESP em horário flexível (segunda a sábado). Cursos de 1 a 7 semanas tem aulas garantidas pela manhã; a partir de 8 semanas pode haver double-banking.</p>','["20 aulas de General English em grupo (09:15–12:45)", "5 aulas individuais da área profissional", "Análise de necessidades no primeiro dia", "Duração de 1 a 11 semanas"]'::jsonb);
    insert into price_template (tenant_id, campus_id, name, price_basis, duration_type, unit, currency, charge_in_tiers, valid_from, status) values (v_tid,'cea43266-51db-5e14-8c4b-b4f24611d620','General English 20 + English for Tourism','duration','flexible','week','EUR',false,'2026-01-01','active') returning id into v_tpl;
    insert into price_tier (price_template_id, min_quantity, unit_price, sort) values (v_tpl,1,450,0);
    insert into price_template_product (price_template_id, product_id) values (v_tpl, v_new);
    insert into fee_product (fee_id, product_id) values (v_fee, v_new);
    insert into fee_product (fee_id, product_id) select f.id, v_new from fee f where f.campus_id='cea43266-51db-5e14-8c4b-b4f24611d620' and f.fee_type='registration' and f.archived_at is null limit 1;
  end if;
end $$;