"use client";

import Link from "next/link";
import BottomNav from "@/components/BottomNav";

type Contrato = {
  id: string;
    nome: string | null;
      valor_total: number | null;
        moeda: string | null;
        };

        type InicioClientProps = {
          nomeCompleto: string | null;
            contrato: Contrato | null;
            };

            const LOGO_URL = "https://exp-tour.com/wp-content/uploads/2026/04/EXP-Tour-Original-Logo.svg";

            function saudacaoPorHorario(): string {
              const hora = new Date().getHours();
                if (hora < 12) return "Bom dia";
                  if (hora < 18) return "Boa tarde";
                    return "Boa noite";
                    }

                    function primeiroNome(nomeCompleto: string | null): string {
                      if (!nomeCompleto) return "";
                        return nomeCompleto.trim().split(" ")[0];
                        }

                        function formatarMoeda(valor: number, moeda: string): string {
                          try {
                              return valor.toLocaleString("pt-BR", { style: "currency", currency: moeda });
                                } catch (erro) {
                                    return valor.toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
                                      }
                                      }

                                      const ETAPAS_JORNADA = [
                                        "Contrato",
                                          "Matricula",
                                            "Acomodacao",
                                              "Visto",
                                                "Pre-embarque",
                                                  "Durante a viagem",
                                                    "Retorno",
                                                    ];

                                                    export default function InicioClient(props: InicioClientProps) {
                                                      const nomeCompleto = props.nomeCompleto;
                                                        const contrato = props.contrato;
                                                          const nome = primeiroNome(nomeCompleto);
                                                            const etapaAtualIndex = contrato ? 1 : 0;

                                                              return (
                                                                  <div className="min-h-screen bg-white pb-24">
                                                                        <header className="flex items-center justify-between border-b border-neutral-100 px-4 py-3">
                                                                                <img src={LOGO_URL} alt="EXP TOUR" className="h-6" />
                                                                                        <div className="flex h-8 w-8 items-center justify-center rounded-full bg-brand text-xs font-medium text-white">
                                                                                                  {nome ? nome.charAt(0).toUpperCase() : "?"}
                                                                                                          </div>
                                                                                                                </header>
                                                                                                                
                                                                                                                      <main className="mx-auto max-w-md px-4 py-6">
                                                                                                                              <h1 className="font-serif text-2xl text-brand">
                                                                                                                                        {saudacaoPorHorario()}
                                                                                                                                                  {nome ? ", " + nome : ""}
                                                                                                                                                          </h1>
                                                                                                                                                                  <p className="mt-1 text-sm text-neutral-500">
                                                                                                                                                                            {contrato && contrato.nome ? contrato.nome : "Sua jornada com a EXP Tour"}
                                                                                                                                                                                    </p>
                                                                                                                                                                                    
                                                                                                                                                                                            {contrato ? (
                                                                                                                                                                                                      <div className="mt-6 rounded-xl bg-brand p-5 text-brand-cream">
                                                                                                                                                                                                                  <p className="text-xs uppercase tracking-wide text-brand-gold">Seu programa</p>
                                                                                                                                                                                                                              <p className="mt-2 text-lg font-medium">{contrato.nome ? contrato.nome : "Programa EXP Tour"}</p>
                                                                                                                                                                                                                                          {contrato.valor_total ? (
                                                                                                                                                                                                                                                        <p className="mt-1 text-sm text-brand-cream/80">
                                                                                                                                                                                                                                                                        Valor total: {formatarMoeda(contrato.valor_total, contrato.moeda || "BRL")}
                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                  ) : null}
                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                    ) : (
                                                                                                                                                                                                                                                                                                                              <div className="mt-6 rounded-xl border border-dashed border-neutral-200 p-5 text-sm text-neutral-500">
                                                                                                                                                                                                                                                                                                                                          Ainda nao encontramos um contrato vinculado ao seu CPF. Fale com sua consultora se
                                                                                                                                                                                                                                                                                                                                                      voce acredita que isso e um engano.
                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                <div className="mt-6 rounded-xl border border-neutral-200 p-5">
                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-xs uppercase tracking-wide text-brand-gold">Seu proximo passo</p>
                                                                                                                                                                                                                                                                                                                                                                                                    <h2 className="mt-1 text-lg font-medium text-brand">Acompanhe Financeiro e Docs</h2>
                                                                                                                                                                                                                                                                                                                                                                                                              <p className="mt-1 text-sm text-neutral-500">
                                                                                                                                                                                                                                                                                                                                                                                                                          Veja suas parcelas, contratos e documentos na aba Financeiro e na aba Docs.
                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                              <Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                          href="/parcelas"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="mt-4 inline-block rounded-md bg-brand px-4 py-2 text-sm font-medium text-white hover:opacity-90"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Ir para Financeiro e Docs
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="mt-6 rounded-xl border border-neutral-200 p-5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="mb-4 flex items-center justify-between">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h2 className="text-base font-medium text-brand">Sua jornada</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span className="text-xs text-neutral-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {etapaAtualIndex} de {ETAPAS_JORNADA.length} concluidas
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <ol className="space-y-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {ETAPAS_JORNADA.map(function (etapa, index) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const concluida = index < etapaAtualIndex;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const emAndamento = index === etapaAtualIndex;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const bolinha = concluida
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ? "bg-brand text-white"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            : emAndamento
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ? "border-2 border-brand"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            : "border border-neutral-300";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const textoClasse = emAndamento ? "font-medium text-brand" : "text-neutral-500";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <li key={etapa} className="flex items-center gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span className={"flex h-5 w-5 flex-shrink-0 items-center justify-center rounded-full text-[10px] " + bolinha}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {concluida ? "OK" : ""}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className={"text-sm " + textoClasse}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {etapa}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {emAndamento ? " (em andamento)" : ""}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </ol>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <BottomNav />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
